// Autogenerated from Pigeon (v17.3.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#ifndef PIGEON_MESSAGES_G_H_
#define PIGEON_MESSAGES_G_H_
#include <flutter/basic_message_channel.h>
#include <flutter/binary_messenger.h>
#include <flutter/encodable_value.h>
#include <flutter/standard_message_codec.h>

#include <map>
#include <optional>
#include <string>

namespace firebase_core_webos {


// Generated class from Pigeon.

class FlutterError {
 public:
  explicit FlutterError(const std::string& code)
    : code_(code) {}
  explicit FlutterError(const std::string& code, const std::string& message)
    : code_(code), message_(message) {}
  explicit FlutterError(const std::string& code, const std::string& message, const flutter::EncodableValue& details)
    : code_(code), message_(message), details_(details) {}

  const std::string& code() const { return code_; }
  const std::string& message() const { return message_; }
  const flutter::EncodableValue& details() const { return details_; }

 private:
  std::string code_;
  std::string message_;
  flutter::EncodableValue details_;
};

template<class T> class ErrorOr {
 public:
  ErrorOr(const T& rhs) : v_(rhs) {}
  ErrorOr(const T&& rhs) : v_(std::move(rhs)) {}
  ErrorOr(const FlutterError& rhs) : v_(rhs) {}
  ErrorOr(const FlutterError&& rhs) : v_(std::move(rhs)) {}

  bool has_error() const { return std::holds_alternative<FlutterError>(v_); }
  const T& value() const { return std::get<T>(v_); };
  const FlutterError& error() const { return std::get<FlutterError>(v_); };

 private:
  friend class FirebaseCoreHostApi;
  ErrorOr() = default;
  T TakeValue() && { return std::get<T>(std::move(v_)); }

  std::variant<T, FlutterError> v_;
};


// All configurable options for a Firebase App.
//
// Generated class from Pigeon that represents data sent in messages.
class FirebaseOptionsPigeon {
 public:
  // Constructs an object setting all non-nullable fields.
  explicit FirebaseOptionsPigeon(
    const std::string& api_key,
    const std::string& app_id,
    const std::string& project_id);

  // Constructs an object setting all fields.
  explicit FirebaseOptionsPigeon(
    const std::string& api_key,
    const std::string& app_id,
    const std::string& project_id,
    const std::string* messaging_sender_id,
    const std::string* database_url,
    const std::string* storage_bucket,
    const std::string* auth_domain);

  const std::string& api_key() const;
  void set_api_key(std::string_view value_arg);

  const std::string& app_id() const;
  void set_app_id(std::string_view value_arg);

  const std::string& project_id() const;
  void set_project_id(std::string_view value_arg);

  const std::string* messaging_sender_id() const;
  void set_messaging_sender_id(const std::string_view* value_arg);
  void set_messaging_sender_id(std::string_view value_arg);

  const std::string* database_url() const;
  void set_database_url(const std::string_view* value_arg);
  void set_database_url(std::string_view value_arg);

  const std::string* storage_bucket() const;
  void set_storage_bucket(const std::string_view* value_arg);
  void set_storage_bucket(std::string_view value_arg);

  const std::string* auth_domain() const;
  void set_auth_domain(const std::string_view* value_arg);
  void set_auth_domain(std::string_view value_arg);


 private:
  static FirebaseOptionsPigeon FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class FirebaseAppPigeon;
  friend class FirebaseCoreHostApi;
  friend class FirebaseCoreHostApiCodecSerializer;
  std::string api_key_;
  std::string app_id_;
  std::string project_id_;
  std::optional<std::string> messaging_sender_id_;
  std::optional<std::string> database_url_;
  std::optional<std::string> storage_bucket_;
  std::optional<std::string> auth_domain_;

};


// Represents an initialized Firebase App returned to Dart.
//
// Generated class from Pigeon that represents data sent in messages.
class FirebaseAppPigeon {
 public:
  // Constructs an object setting all fields.
  explicit FirebaseAppPigeon(
    const std::string& name,
    const FirebaseOptionsPigeon& options);

  ~FirebaseAppPigeon() = default;
  FirebaseAppPigeon(const FirebaseAppPigeon& other);
  FirebaseAppPigeon& operator=(const FirebaseAppPigeon& other);
  FirebaseAppPigeon(FirebaseAppPigeon&& other) = default;
  FirebaseAppPigeon& operator=(FirebaseAppPigeon&& other) noexcept = default;
  // App name – "[DEFAULT]" for the default app.
  const std::string& name() const;
  void set_name(std::string_view value_arg);

  // The options that were used to initialize this app.
  const FirebaseOptionsPigeon& options() const;
  void set_options(const FirebaseOptionsPigeon& value_arg);


 private:
  static FirebaseAppPigeon FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class FirebaseCoreHostApi;
  friend class FirebaseCoreHostApiCodecSerializer;
  std::string name_;
  std::unique_ptr<FirebaseOptionsPigeon> options_;

};

class FirebaseCoreHostApiCodecSerializer : public flutter::StandardCodecSerializer {
 public:
  FirebaseCoreHostApiCodecSerializer();
  inline static FirebaseCoreHostApiCodecSerializer& GetInstance() {
    static FirebaseCoreHostApiCodecSerializer sInstance;
    return sInstance;
  }

  void WriteValue(
    const flutter::EncodableValue& value,
    flutter::ByteStreamWriter* stream) const override;

 protected:
  flutter::EncodableValue ReadValueOfType(
    uint8_t type,
    flutter::ByteStreamReader* stream) const override;

};

// Generated interface from Pigeon that represents a handler of messages from Flutter.
class FirebaseCoreHostApi {
 public:
  FirebaseCoreHostApi(const FirebaseCoreHostApi&) = delete;
  FirebaseCoreHostApi& operator=(const FirebaseCoreHostApi&) = delete;
  virtual ~FirebaseCoreHostApi() {}
  virtual void SetDataDirectory(
    const std::string& data_directory,
    std::function<void(std::optional<FlutterError> reply)> result) = 0;
  virtual void InitializeApp(
    const std::string& app_name,
    const FirebaseOptionsPigeon& options,
    std::function<void(ErrorOr<FirebaseAppPigeon> reply)> result) = 0;
  virtual void GetApp(
    const std::string& app_name,
    std::function<void(ErrorOr<FirebaseAppPigeon> reply)> result) = 0;
  virtual void DeleteApp(
    const std::string& app_name,
    std::function<void(std::optional<FlutterError> reply)> result) = 0;

  // The codec used by FirebaseCoreHostApi.
  static const flutter::StandardMessageCodec& GetCodec();
  // Sets up an instance of `FirebaseCoreHostApi` to handle messages through the `binary_messenger`.
  static void SetUp(
    flutter::BinaryMessenger* binary_messenger,
    FirebaseCoreHostApi* api);
  static flutter::EncodableValue WrapError(std::string_view error_message);
  static flutter::EncodableValue WrapError(const FlutterError& error);

 protected:
  FirebaseCoreHostApi() = default;

};
}  // namespace firebase_core_webos
#endif  // PIGEON_MESSAGES_G_H_
