// Autogenerated from Pigeon (v17.3.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#undef _HAS_EXCEPTIONS

#include "messages.g.h"

#include <flutter/basic_message_channel.h>
#include <flutter/binary_messenger.h>
#include <flutter/encodable_value.h>
#include <flutter/standard_message_codec.h>

#include <map>
#include <optional>
#include <string>

namespace firebase_core_webos {
using flutter::BasicMessageChannel;
using flutter::CustomEncodableValue;
using flutter::EncodableList;
using flutter::EncodableMap;
using flutter::EncodableValue;

FlutterError CreateConnectionError(const std::string channel_name) {
    return FlutterError(
        "channel-error",
        "Unable to establish connection on channel: '" + channel_name + "'.",
        EncodableValue(""));
}

// FirebaseOptionsPigeon

FirebaseOptionsPigeon::FirebaseOptionsPigeon(
  const std::string& api_key,
  const std::string& app_id,
  const std::string& project_id)
 : api_key_(api_key),
    app_id_(app_id),
    project_id_(project_id) {}

FirebaseOptionsPigeon::FirebaseOptionsPigeon(
  const std::string& api_key,
  const std::string& app_id,
  const std::string& project_id,
  const std::string* messaging_sender_id,
  const std::string* database_url,
  const std::string* storage_bucket,
  const std::string* auth_domain)
 : api_key_(api_key),
    app_id_(app_id),
    project_id_(project_id),
    messaging_sender_id_(messaging_sender_id ? std::optional<std::string>(*messaging_sender_id) : std::nullopt),
    database_url_(database_url ? std::optional<std::string>(*database_url) : std::nullopt),
    storage_bucket_(storage_bucket ? std::optional<std::string>(*storage_bucket) : std::nullopt),
    auth_domain_(auth_domain ? std::optional<std::string>(*auth_domain) : std::nullopt) {}

const std::string& FirebaseOptionsPigeon::api_key() const {
  return api_key_;
}

void FirebaseOptionsPigeon::set_api_key(std::string_view value_arg) {
  api_key_ = value_arg;
}


const std::string& FirebaseOptionsPigeon::app_id() const {
  return app_id_;
}

void FirebaseOptionsPigeon::set_app_id(std::string_view value_arg) {
  app_id_ = value_arg;
}


const std::string& FirebaseOptionsPigeon::project_id() const {
  return project_id_;
}

void FirebaseOptionsPigeon::set_project_id(std::string_view value_arg) {
  project_id_ = value_arg;
}


const std::string* FirebaseOptionsPigeon::messaging_sender_id() const {
  return messaging_sender_id_ ? &(*messaging_sender_id_) : nullptr;
}

void FirebaseOptionsPigeon::set_messaging_sender_id(const std::string_view* value_arg) {
  messaging_sender_id_ = value_arg ? std::optional<std::string>(*value_arg) : std::nullopt;
}

void FirebaseOptionsPigeon::set_messaging_sender_id(std::string_view value_arg) {
  messaging_sender_id_ = value_arg;
}


const std::string* FirebaseOptionsPigeon::database_url() const {
  return database_url_ ? &(*database_url_) : nullptr;
}

void FirebaseOptionsPigeon::set_database_url(const std::string_view* value_arg) {
  database_url_ = value_arg ? std::optional<std::string>(*value_arg) : std::nullopt;
}

void FirebaseOptionsPigeon::set_database_url(std::string_view value_arg) {
  database_url_ = value_arg;
}


const std::string* FirebaseOptionsPigeon::storage_bucket() const {
  return storage_bucket_ ? &(*storage_bucket_) : nullptr;
}

void FirebaseOptionsPigeon::set_storage_bucket(const std::string_view* value_arg) {
  storage_bucket_ = value_arg ? std::optional<std::string>(*value_arg) : std::nullopt;
}

void FirebaseOptionsPigeon::set_storage_bucket(std::string_view value_arg) {
  storage_bucket_ = value_arg;
}


const std::string* FirebaseOptionsPigeon::auth_domain() const {
  return auth_domain_ ? &(*auth_domain_) : nullptr;
}

void FirebaseOptionsPigeon::set_auth_domain(const std::string_view* value_arg) {
  auth_domain_ = value_arg ? std::optional<std::string>(*value_arg) : std::nullopt;
}

void FirebaseOptionsPigeon::set_auth_domain(std::string_view value_arg) {
  auth_domain_ = value_arg;
}


EncodableList FirebaseOptionsPigeon::ToEncodableList() const {
  EncodableList list;
  list.reserve(7);
  list.push_back(EncodableValue(api_key_));
  list.push_back(EncodableValue(app_id_));
  list.push_back(EncodableValue(project_id_));
  list.push_back(messaging_sender_id_ ? EncodableValue(*messaging_sender_id_) : EncodableValue());
  list.push_back(database_url_ ? EncodableValue(*database_url_) : EncodableValue());
  list.push_back(storage_bucket_ ? EncodableValue(*storage_bucket_) : EncodableValue());
  list.push_back(auth_domain_ ? EncodableValue(*auth_domain_) : EncodableValue());
  return list;
}

FirebaseOptionsPigeon FirebaseOptionsPigeon::FromEncodableList(const EncodableList& list) {
  FirebaseOptionsPigeon decoded(
    std::get<std::string>(list[0]),
    std::get<std::string>(list[1]),
    std::get<std::string>(list[2]));
  auto& encodable_messaging_sender_id = list[3];
  if (!encodable_messaging_sender_id.IsNull()) {
    decoded.set_messaging_sender_id(std::get<std::string>(encodable_messaging_sender_id));
  }
  auto& encodable_database_url = list[4];
  if (!encodable_database_url.IsNull()) {
    decoded.set_database_url(std::get<std::string>(encodable_database_url));
  }
  auto& encodable_storage_bucket = list[5];
  if (!encodable_storage_bucket.IsNull()) {
    decoded.set_storage_bucket(std::get<std::string>(encodable_storage_bucket));
  }
  auto& encodable_auth_domain = list[6];
  if (!encodable_auth_domain.IsNull()) {
    decoded.set_auth_domain(std::get<std::string>(encodable_auth_domain));
  }
  return decoded;
}

// FirebaseAppPigeon

FirebaseAppPigeon::FirebaseAppPigeon(
  const std::string& name,
  const FirebaseOptionsPigeon& options)
 : name_(name),
    options_(std::make_unique<FirebaseOptionsPigeon>(options)) {}

FirebaseAppPigeon::FirebaseAppPigeon(const FirebaseAppPigeon& other)
 : name_(other.name_),
    options_(std::make_unique<FirebaseOptionsPigeon>(*other.options_)) {}

FirebaseAppPigeon& FirebaseAppPigeon::operator=(const FirebaseAppPigeon& other) {
  name_ = other.name_;
  options_ = std::make_unique<FirebaseOptionsPigeon>(*other.options_);
  return *this;
}

const std::string& FirebaseAppPigeon::name() const {
  return name_;
}

void FirebaseAppPigeon::set_name(std::string_view value_arg) {
  name_ = value_arg;
}


const FirebaseOptionsPigeon& FirebaseAppPigeon::options() const {
  return *options_;
}

void FirebaseAppPigeon::set_options(const FirebaseOptionsPigeon& value_arg) {
  options_ = std::make_unique<FirebaseOptionsPigeon>(value_arg);
}


EncodableList FirebaseAppPigeon::ToEncodableList() const {
  EncodableList list;
  list.reserve(2);
  list.push_back(EncodableValue(name_));
  list.push_back(EncodableValue(options_->ToEncodableList()));
  return list;
}

FirebaseAppPigeon FirebaseAppPigeon::FromEncodableList(const EncodableList& list) {
  FirebaseAppPigeon decoded(
    std::get<std::string>(list[0]),
    FirebaseOptionsPigeon::FromEncodableList(std::get<EncodableList>(list[1])));
  return decoded;
}


FirebaseCoreHostApiCodecSerializer::FirebaseCoreHostApiCodecSerializer() {}

EncodableValue FirebaseCoreHostApiCodecSerializer::ReadValueOfType(
  uint8_t type,
  flutter::ByteStreamReader* stream) const {
  switch (type) {
    case 128:
      return CustomEncodableValue(FirebaseAppPigeon::FromEncodableList(std::get<EncodableList>(ReadValue(stream))));
    case 129:
      return CustomEncodableValue(FirebaseOptionsPigeon::FromEncodableList(std::get<EncodableList>(ReadValue(stream))));
    default:
      return flutter::StandardCodecSerializer::ReadValueOfType(type, stream);
  }
}

void FirebaseCoreHostApiCodecSerializer::WriteValue(
  const EncodableValue& value,
  flutter::ByteStreamWriter* stream) const {
  if (const CustomEncodableValue* custom_value = std::get_if<CustomEncodableValue>(&value)) {
    if (custom_value->type() == typeid(FirebaseAppPigeon)) {
      stream->WriteByte(128);
      WriteValue(EncodableValue(std::any_cast<FirebaseAppPigeon>(*custom_value).ToEncodableList()), stream);
      return;
    }
    if (custom_value->type() == typeid(FirebaseOptionsPigeon)) {
      stream->WriteByte(129);
      WriteValue(EncodableValue(std::any_cast<FirebaseOptionsPigeon>(*custom_value).ToEncodableList()), stream);
      return;
    }
  }
  flutter::StandardCodecSerializer::WriteValue(value, stream);
}

/// The codec used by FirebaseCoreHostApi.
const flutter::StandardMessageCodec& FirebaseCoreHostApi::GetCodec() {
  return flutter::StandardMessageCodec::GetInstance(&FirebaseCoreHostApiCodecSerializer::GetInstance());
}

// Sets up an instance of `FirebaseCoreHostApi` to handle messages through the `binary_messenger`.
void FirebaseCoreHostApi::SetUp(
  flutter::BinaryMessenger* binary_messenger,
  FirebaseCoreHostApi* api) {
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.firebase_core_webos.FirebaseCoreHostApi.setDataDirectory", &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_data_directory_arg = args.at(0);
          if (encodable_data_directory_arg.IsNull()) {
            reply(WrapError("data_directory_arg unexpectedly null."));
            return;
          }
          const auto& data_directory_arg = std::get<std::string>(encodable_data_directory_arg);
          api->SetDataDirectory(data_directory_arg, [reply](std::optional<FlutterError>&& output) {
            if (output.has_value()) {
              reply(WrapError(output.value()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(EncodableValue());
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.firebase_core_webos.FirebaseCoreHostApi.initializeApp", &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_app_name_arg = args.at(0);
          if (encodable_app_name_arg.IsNull()) {
            reply(WrapError("app_name_arg unexpectedly null."));
            return;
          }
          const auto& app_name_arg = std::get<std::string>(encodable_app_name_arg);
          const auto& encodable_options_arg = args.at(1);
          if (encodable_options_arg.IsNull()) {
            reply(WrapError("options_arg unexpectedly null."));
            return;
          }
          const auto& options_arg = std::any_cast<const FirebaseOptionsPigeon&>(std::get<CustomEncodableValue>(encodable_options_arg));
          api->InitializeApp(app_name_arg, options_arg, [reply](ErrorOr<FirebaseAppPigeon>&& output) {
            if (output.has_error()) {
              reply(WrapError(output.error()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(CustomEncodableValue(std::move(output).TakeValue()));
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.firebase_core_webos.FirebaseCoreHostApi.getApp", &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_app_name_arg = args.at(0);
          if (encodable_app_name_arg.IsNull()) {
            reply(WrapError("app_name_arg unexpectedly null."));
            return;
          }
          const auto& app_name_arg = std::get<std::string>(encodable_app_name_arg);
          api->GetApp(app_name_arg, [reply](ErrorOr<FirebaseAppPigeon>&& output) {
            if (output.has_error()) {
              reply(WrapError(output.error()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(CustomEncodableValue(std::move(output).TakeValue()));
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.firebase_core_webos.FirebaseCoreHostApi.deleteApp", &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_app_name_arg = args.at(0);
          if (encodable_app_name_arg.IsNull()) {
            reply(WrapError("app_name_arg unexpectedly null."));
            return;
          }
          const auto& app_name_arg = std::get<std::string>(encodable_app_name_arg);
          api->DeleteApp(app_name_arg, [reply](std::optional<FlutterError>&& output) {
            if (output.has_value()) {
              reply(WrapError(output.value()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(EncodableValue());
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
}

EncodableValue FirebaseCoreHostApi::WrapError(std::string_view error_message) {
  return EncodableValue(EncodableList{
    EncodableValue(std::string(error_message)),
    EncodableValue("Error"),
    EncodableValue()
  });
}

EncodableValue FirebaseCoreHostApi::WrapError(const FlutterError& error) {
  return EncodableValue(EncodableList{
    EncodableValue(error.code()),
    EncodableValue(error.message()),
    error.details()
  });
}

}  // namespace firebase_core_webos
