// Autogenerated from Pigeon (v17.3.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import, no_leading_underscores_for_local_identifiers

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

PlatformException _createConnectionError(String channelName) {
  return PlatformException(
    code: 'channel-error',
    message: 'Unable to establish connection on channel: "$channelName".',
  );
}

List<Object?> wrapResponse({Object? result, PlatformException? error, bool empty = false}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}

/// Document change type
enum PigeonDocumentChangeType {
  added,
  modified,
  removed,
}

enum PigeonTransactionResult {
  success,
  failure,
}

/// Firestore settings configuration
class PigeonFirestoreSettings {
  PigeonFirestoreSettings({
    required this.host,
    required this.sslEnabled,
    required this.persistenceEnabled,
    required this.cacheSizeBytes,
  });

  String host;

  bool sslEnabled;

  bool persistenceEnabled;

  int cacheSizeBytes;

  Object encode() {
    return <Object?>[
      host,
      sslEnabled,
      persistenceEnabled,
      cacheSizeBytes,
    ];
  }

  static PigeonFirestoreSettings decode(Object result) {
    result as List<Object?>;
    return PigeonFirestoreSettings(
      host: result[0]! as String,
      sslEnabled: result[1]! as bool,
      persistenceEnabled: result[2]! as bool,
      cacheSizeBytes: result[3]! as int,
    );
  }
}

/// Snapshot metadata
class PigeonSnapshotMetadata {
  PigeonSnapshotMetadata({
    required this.hasPendingWrites,
    required this.isFromCache,
  });

  bool hasPendingWrites;

  bool isFromCache;

  Object encode() {
    return <Object?>[
      hasPendingWrites,
      isFromCache,
    ];
  }

  static PigeonSnapshotMetadata decode(Object result) {
    result as List<Object?>;
    return PigeonSnapshotMetadata(
      hasPendingWrites: result[0]! as bool,
      isFromCache: result[1]! as bool,
    );
  }
}

/// Document snapshot data
class PigeonDocumentSnapshot {
  PigeonDocumentSnapshot({
    required this.path,
    this.data,
    required this.metadata,
    required this.exists,
  });

  String path;

  Map<String?, Object?>? data;

  PigeonSnapshotMetadata metadata;

  bool exists;

  Object encode() {
    return <Object?>[
      path,
      data,
      metadata.encode(),
      exists,
    ];
  }

  static PigeonDocumentSnapshot decode(Object result) {
    result as List<Object?>;
    return PigeonDocumentSnapshot(
      path: result[0]! as String,
      data: (result[1] as Map<Object?, Object?>?)?.cast<String?, Object?>(),
      metadata: PigeonSnapshotMetadata.decode(result[2]! as List<Object?>),
      exists: result[3]! as bool,
    );
  }
}

/// Document change
class PigeonDocumentChange {
  PigeonDocumentChange({
    required this.type,
    required this.document,
    required this.oldIndex,
    required this.newIndex,
  });

  PigeonDocumentChangeType type;

  PigeonDocumentSnapshot document;

  int oldIndex;

  int newIndex;

  Object encode() {
    return <Object?>[
      type.index,
      document.encode(),
      oldIndex,
      newIndex,
    ];
  }

  static PigeonDocumentChange decode(Object result) {
    result as List<Object?>;
    return PigeonDocumentChange(
      type: PigeonDocumentChangeType.values[result[0]! as int],
      document: PigeonDocumentSnapshot.decode(result[1]! as List<Object?>),
      oldIndex: result[2]! as int,
      newIndex: result[3]! as int,
    );
  }
}

/// Query snapshot
class PigeonQuerySnapshot {
  PigeonQuerySnapshot({
    required this.documents,
    required this.documentChanges,
    required this.metadata,
  });

  List<PigeonDocumentSnapshot?> documents;

  List<PigeonDocumentChange?> documentChanges;

  PigeonSnapshotMetadata metadata;

  Object encode() {
    return <Object?>[
      documents,
      documentChanges,
      metadata.encode(),
    ];
  }

  static PigeonQuerySnapshot decode(Object result) {
    result as List<Object?>;
    return PigeonQuerySnapshot(
      documents: (result[0] as List<Object?>?)!.cast<PigeonDocumentSnapshot?>(),
      documentChanges: (result[1] as List<Object?>?)!.cast<PigeonDocumentChange?>(),
      metadata: PigeonSnapshotMetadata.decode(result[2]! as List<Object?>),
    );
  }
}

/// Get options
class PigeonGetOptions {
  PigeonGetOptions({
    required this.source,
  });

  String source;

  Object encode() {
    return <Object?>[
      source,
    ];
  }

  static PigeonGetOptions decode(Object result) {
    result as List<Object?>;
    return PigeonGetOptions(
      source: result[0]! as String,
    );
  }
}

/// Set options
class PigeonSetOptions {
  PigeonSetOptions({
    required this.merge,
    this.mergeFields,
  });

  bool merge;

  List<String?>? mergeFields;

  Object encode() {
    return <Object?>[
      merge,
      mergeFields,
    ];
  }

  static PigeonSetOptions decode(Object result) {
    result as List<Object?>;
    return PigeonSetOptions(
      merge: result[0]! as bool,
      mergeFields: (result[1] as List<Object?>?)?.cast<String?>(),
    );
  }
}

/// Transaction update data
class PigeonTransactionUpdate {
  PigeonTransactionUpdate({
    required this.type,
    required this.path,
    this.data,
  });

  String type;

  String path;

  Map<String?, Object?>? data;

  Object encode() {
    return <Object?>[
      type,
      path,
      data,
    ];
  }

  static PigeonTransactionUpdate decode(Object result) {
    result as List<Object?>;
    return PigeonTransactionUpdate(
      type: result[0]! as String,
      path: result[1]! as String,
      data: (result[2] as Map<Object?, Object?>?)?.cast<String?, Object?>(),
    );
  }
}

/// Aggregate query result
class PigeonAggregateQuerySnapshot {
  PigeonAggregateQuerySnapshot({
    required this.count,
    this.sum,
    this.average,
  });

  int count;

  /// Sum aggregation results: list of {field: string, value: double}
  List<PigeonAggregateResult?>? sum;

  /// Average aggregation results: list of {field: string, value: double}
  List<PigeonAggregateResult?>? average;

  Object encode() {
    return <Object?>[
      count,
      sum,
      average,
    ];
  }

  static PigeonAggregateQuerySnapshot decode(Object result) {
    result as List<Object?>;
    return PigeonAggregateQuerySnapshot(
      count: result[0]! as int,
      sum: (result[1] as List<Object?>?)?.cast<PigeonAggregateResult?>(),
      average: (result[2] as List<Object?>?)?.cast<PigeonAggregateResult?>(),
    );
  }
}

/// A single aggregate result (field name + value)
class PigeonAggregateResult {
  PigeonAggregateResult({
    required this.field,
    required this.value,
  });

  String field;

  double value;

  Object encode() {
    return <Object?>[
      field,
      value,
    ];
  }

  static PigeonAggregateResult decode(Object result) {
    result as List<Object?>;
    return PigeonAggregateResult(
      field: result[0]! as String,
      value: result[1]! as double,
    );
  }
}

/// Query parameters for building queries
class PigeonQueryParameters {
  PigeonQueryParameters({
    this.where,
    this.orderBy,
    this.limit,
    this.limitToLast,
    this.startAt,
    this.startAfter,
    this.endAt,
    this.endBefore,
  });

  List<PigeonQueryFilter?>? where;

  List<PigeonQueryOrder?>? orderBy;

  int? limit;

  int? limitToLast;

  List<Object?>? startAt;

  List<Object?>? startAfter;

  List<Object?>? endAt;

  List<Object?>? endBefore;

  Object encode() {
    return <Object?>[
      where,
      orderBy,
      limit,
      limitToLast,
      startAt,
      startAfter,
      endAt,
      endBefore,
    ];
  }

  static PigeonQueryParameters decode(Object result) {
    result as List<Object?>;
    return PigeonQueryParameters(
      where: (result[0] as List<Object?>?)?.cast<PigeonQueryFilter?>(),
      orderBy: (result[1] as List<Object?>?)?.cast<PigeonQueryOrder?>(),
      limit: result[2] as int?,
      limitToLast: result[3] as int?,
      startAt: (result[4] as List<Object?>?)?.cast<Object?>(),
      startAfter: (result[5] as List<Object?>?)?.cast<Object?>(),
      endAt: (result[6] as List<Object?>?)?.cast<Object?>(),
      endBefore: (result[7] as List<Object?>?)?.cast<Object?>(),
    );
  }
}

/// Query filter
class PigeonQueryFilter {
  PigeonQueryFilter({
    required this.field,
    required this.op,
    this.value,
  });

  String field;

  String op;

  Object? value;

  Object encode() {
    return <Object?>[
      field,
      op,
      value,
    ];
  }

  static PigeonQueryFilter decode(Object result) {
    result as List<Object?>;
    return PigeonQueryFilter(
      field: result[0]! as String,
      op: result[1]! as String,
      value: result[2],
    );
  }
}

/// Query order
class PigeonQueryOrder {
  PigeonQueryOrder({
    required this.field,
    required this.descending,
  });

  String field;

  bool descending;

  Object encode() {
    return <Object?>[
      field,
      descending,
    ];
  }

  static PigeonQueryOrder decode(Object result) {
    result as List<Object?>;
    return PigeonQueryOrder(
      field: result[0]! as String,
      descending: result[1]! as bool,
    );
  }
}

class _FirestoreHostApiCodec extends StandardMessageCodec {
  const _FirestoreHostApiCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is PigeonAggregateQuerySnapshot) {
      buffer.putUint8(128);
      writeValue(buffer, value.encode());
    } else if (value is PigeonAggregateResult) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    } else if (value is PigeonDocumentChange) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    } else if (value is PigeonDocumentSnapshot) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    } else if (value is PigeonFirestoreSettings) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    } else if (value is PigeonGetOptions) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    } else if (value is PigeonQueryFilter) {
      buffer.putUint8(134);
      writeValue(buffer, value.encode());
    } else if (value is PigeonQueryOrder) {
      buffer.putUint8(135);
      writeValue(buffer, value.encode());
    } else if (value is PigeonQueryParameters) {
      buffer.putUint8(136);
      writeValue(buffer, value.encode());
    } else if (value is PigeonQuerySnapshot) {
      buffer.putUint8(137);
      writeValue(buffer, value.encode());
    } else if (value is PigeonSetOptions) {
      buffer.putUint8(138);
      writeValue(buffer, value.encode());
    } else if (value is PigeonSnapshotMetadata) {
      buffer.putUint8(139);
      writeValue(buffer, value.encode());
    } else if (value is PigeonTransactionUpdate) {
      buffer.putUint8(140);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 128: 
        return PigeonAggregateQuerySnapshot.decode(readValue(buffer)!);
      case 129: 
        return PigeonAggregateResult.decode(readValue(buffer)!);
      case 130: 
        return PigeonDocumentChange.decode(readValue(buffer)!);
      case 131: 
        return PigeonDocumentSnapshot.decode(readValue(buffer)!);
      case 132: 
        return PigeonFirestoreSettings.decode(readValue(buffer)!);
      case 133: 
        return PigeonGetOptions.decode(readValue(buffer)!);
      case 134: 
        return PigeonQueryFilter.decode(readValue(buffer)!);
      case 135: 
        return PigeonQueryOrder.decode(readValue(buffer)!);
      case 136: 
        return PigeonQueryParameters.decode(readValue(buffer)!);
      case 137: 
        return PigeonQuerySnapshot.decode(readValue(buffer)!);
      case 138: 
        return PigeonSetOptions.decode(readValue(buffer)!);
      case 139: 
        return PigeonSnapshotMetadata.decode(readValue(buffer)!);
      case 140: 
        return PigeonTransactionUpdate.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class FirestoreHostApi {
  /// Constructor for [FirestoreHostApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  FirestoreHostApi({BinaryMessenger? binaryMessenger})
      : __pigeon_binaryMessenger = binaryMessenger;
  final BinaryMessenger? __pigeon_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _FirestoreHostApiCodec();

  /// Initialize Firestore instance
  Future<void> initializeFirestore(String appName, String databaseId) async {
    const String __pigeon_channelName = 'dev.flutter.pigeon.firebase_firestore_webos.FirestoreHostApi.initializeFirestore';
    final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(<Object?>[appName, databaseId]) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else {
      return;
    }
  }

  /// Set Firestore settings (must be called before any other operation)
  Future<void> setSettings(String appName, String databaseId, PigeonFirestoreSettings settings) async {
    const String __pigeon_channelName = 'dev.flutter.pigeon.firebase_firestore_webos.FirestoreHostApi.setSettings';
    final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(<Object?>[appName, databaseId, settings]) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else {
      return;
    }
  }

  /// Enable network
  Future<void> enableNetwork(String appName, String databaseId) async {
    const String __pigeon_channelName = 'dev.flutter.pigeon.firebase_firestore_webos.FirestoreHostApi.enableNetwork';
    final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(<Object?>[appName, databaseId]) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else {
      return;
    }
  }

  /// Disable network
  Future<void> disableNetwork(String appName, String databaseId) async {
    const String __pigeon_channelName = 'dev.flutter.pigeon.firebase_firestore_webos.FirestoreHostApi.disableNetwork';
    final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(<Object?>[appName, databaseId]) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else {
      return;
    }
  }

  /// Clear persistence
  Future<void> clearPersistence(String appName, String databaseId) async {
    const String __pigeon_channelName = 'dev.flutter.pigeon.firebase_firestore_webos.FirestoreHostApi.clearPersistence';
    final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(<Object?>[appName, databaseId]) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else {
      return;
    }
  }

  /// Terminate Firestore instance
  Future<void> terminate(String appName, String databaseId) async {
    const String __pigeon_channelName = 'dev.flutter.pigeon.firebase_firestore_webos.FirestoreHostApi.terminate';
    final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(<Object?>[appName, databaseId]) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else {
      return;
    }
  }

  /// Wait for pending writes
  Future<void> waitForPendingWrites(String appName, String databaseId) async {
    const String __pigeon_channelName = 'dev.flutter.pigeon.firebase_firestore_webos.FirestoreHostApi.waitForPendingWrites';
    final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(<Object?>[appName, databaseId]) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else {
      return;
    }
  }

  /// Get a document
  Future<PigeonDocumentSnapshot> documentGet(String appName, String databaseId, String path, PigeonGetOptions options) async {
    const String __pigeon_channelName = 'dev.flutter.pigeon.firebase_firestore_webos.FirestoreHostApi.documentGet';
    final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(<Object?>[appName, databaseId, path, options]) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else if (__pigeon_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (__pigeon_replyList[0] as PigeonDocumentSnapshot?)!;
    }
  }

  /// Set a document
  Future<void> documentSet(String appName, String databaseId, String path, Map<String?, Object?> data, PigeonSetOptions options) async {
    const String __pigeon_channelName = 'dev.flutter.pigeon.firebase_firestore_webos.FirestoreHostApi.documentSet';
    final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(<Object?>[appName, databaseId, path, data, options]) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else {
      return;
    }
  }

  /// Update a document
  Future<void> documentUpdate(String appName, String databaseId, String path, Map<String?, Object?> data) async {
    const String __pigeon_channelName = 'dev.flutter.pigeon.firebase_firestore_webos.FirestoreHostApi.documentUpdate';
    final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(<Object?>[appName, databaseId, path, data]) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else {
      return;
    }
  }

  /// Delete a document
  Future<void> documentDelete(String appName, String databaseId, String path) async {
    const String __pigeon_channelName = 'dev.flutter.pigeon.firebase_firestore_webos.FirestoreHostApi.documentDelete';
    final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(<Object?>[appName, databaseId, path]) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else {
      return;
    }
  }

  /// Start listening to a document
  Future<int> documentAddSnapshotListener(String appName, String databaseId, String path, bool includeMetadataChanges) async {
    const String __pigeon_channelName = 'dev.flutter.pigeon.firebase_firestore_webos.FirestoreHostApi.documentAddSnapshotListener';
    final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(<Object?>[appName, databaseId, path, includeMetadataChanges]) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else if (__pigeon_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (__pigeon_replyList[0] as int?)!;
    }
  }

  /// Query get
  Future<PigeonQuerySnapshot> queryGet(String appName, String databaseId, String path, bool isCollectionGroup, PigeonQueryParameters parameters, PigeonGetOptions options) async {
    const String __pigeon_channelName = 'dev.flutter.pigeon.firebase_firestore_webos.FirestoreHostApi.queryGet';
    final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(<Object?>[appName, databaseId, path, isCollectionGroup, parameters, options]) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else if (__pigeon_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (__pigeon_replyList[0] as PigeonQuerySnapshot?)!;
    }
  }

  /// Start listening to a query
  Future<int> queryAddSnapshotListener(String appName, String databaseId, String path, bool isCollectionGroup, PigeonQueryParameters parameters, bool includeMetadataChanges) async {
    const String __pigeon_channelName = 'dev.flutter.pigeon.firebase_firestore_webos.FirestoreHostApi.queryAddSnapshotListener';
    final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(<Object?>[appName, databaseId, path, isCollectionGroup, parameters, includeMetadataChanges]) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else if (__pigeon_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (__pigeon_replyList[0] as int?)!;
    }
  }

  /// Count aggregate query
  Future<PigeonAggregateQuerySnapshot> queryCount(String appName, String databaseId, String path, bool isCollectionGroup, PigeonQueryParameters parameters) async {
    const String __pigeon_channelName = 'dev.flutter.pigeon.firebase_firestore_webos.FirestoreHostApi.queryCount';
    final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(<Object?>[appName, databaseId, path, isCollectionGroup, parameters]) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else if (__pigeon_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (__pigeon_replyList[0] as PigeonAggregateQuerySnapshot?)!;
    }
  }

  /// Aggregate query (supports count, sum, average)
  /// The aggregateTypes parameter is a list of strings: "count", "sum:fieldName", "avg:fieldName"
  Future<PigeonAggregateQuerySnapshot> queryAggregate(String appName, String databaseId, String path, bool isCollectionGroup, PigeonQueryParameters parameters, List<String?> aggregateTypes) async {
    const String __pigeon_channelName = 'dev.flutter.pigeon.firebase_firestore_webos.FirestoreHostApi.queryAggregate';
    final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(<Object?>[appName, databaseId, path, isCollectionGroup, parameters, aggregateTypes]) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else if (__pigeon_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (__pigeon_replyList[0] as PigeonAggregateQuerySnapshot?)!;
    }
  }

  /// Remove a snapshot listener
  Future<void> removeSnapshotListener(String appName, String databaseId, int listenerId) async {
    const String __pigeon_channelName = 'dev.flutter.pigeon.firebase_firestore_webos.FirestoreHostApi.removeSnapshotListener';
    final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(<Object?>[appName, databaseId, listenerId]) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else {
      return;
    }
  }

  /// Use emulator
  Future<void> useEmulator(String appName, String databaseId, String host, int port) async {
    const String __pigeon_channelName = 'dev.flutter.pigeon.firebase_firestore_webos.FirestoreHostApi.useEmulator';
    final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(<Object?>[appName, databaseId, host, port]) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else {
      return;
    }
  }

  /// Set logging enabled
  Future<void> setLoggingEnabled(String appName, String databaseId, bool enabled) async {
    const String __pigeon_channelName = 'dev.flutter.pigeon.firebase_firestore_webos.FirestoreHostApi.setLoggingEnabled';
    final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(<Object?>[appName, databaseId, enabled]) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else {
      return;
    }
  }

  /// Commit a batch write
  Future<void> batchCommit(String appName, String databaseId, List<PigeonTransactionUpdate?> writes) async {
    const String __pigeon_channelName = 'dev.flutter.pigeon.firebase_firestore_webos.FirestoreHostApi.batchCommit';
    final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(<Object?>[appName, databaseId, writes]) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else {
      return;
    }
  }

  /// Run a transaction
  Future<void> runTransaction(String appName, String databaseId, int transactionId, int maxAttempts) async {
    const String __pigeon_channelName = 'dev.flutter.pigeon.firebase_firestore_webos.FirestoreHostApi.runTransaction';
    final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(<Object?>[appName, databaseId, transactionId, maxAttempts]) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else {
      return;
    }
  }

  /// Get document in transaction
  Future<PigeonDocumentSnapshot> transactionGet(String appName, String databaseId, int transactionId, String path) async {
    const String __pigeon_channelName = 'dev.flutter.pigeon.firebase_firestore_webos.FirestoreHostApi.transactionGet';
    final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(<Object?>[appName, databaseId, transactionId, path]) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else if (__pigeon_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (__pigeon_replyList[0] as PigeonDocumentSnapshot?)!;
    }
  }

  /// Complete transaction with updates
  Future<void> transactionComplete(String appName, String databaseId, int transactionId, PigeonTransactionResult resultType, List<PigeonTransactionUpdate?>? updates) async {
    const String __pigeon_channelName = 'dev.flutter.pigeon.firebase_firestore_webos.FirestoreHostApi.transactionComplete';
    final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(<Object?>[appName, databaseId, transactionId, resultType.index, updates]) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else {
      return;
    }
  }
}

abstract class FirestoreFlutterApi {
  static const MessageCodec<Object?> pigeonChannelCodec = StandardMessageCodec();

  /// Request transaction updates from Dart
  /// Returns JSON-encoded result data or error
  void onTransactionCallback(String appName, String databaseId, int transactionId);

  static void setup(FirestoreFlutterApi? api, {BinaryMessenger? binaryMessenger}) {
    {
      final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.firebase_firestore_webos.FirestoreFlutterApi.onTransactionCallback', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        __pigeon_channel.setMessageHandler(null);
      } else {
        __pigeon_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.firebase_firestore_webos.FirestoreFlutterApi.onTransactionCallback was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final String? arg_appName = (args[0] as String?);
          assert(arg_appName != null,
              'Argument for dev.flutter.pigeon.firebase_firestore_webos.FirestoreFlutterApi.onTransactionCallback was null, expected non-null String.');
          final String? arg_databaseId = (args[1] as String?);
          assert(arg_databaseId != null,
              'Argument for dev.flutter.pigeon.firebase_firestore_webos.FirestoreFlutterApi.onTransactionCallback was null, expected non-null String.');
          final int? arg_transactionId = (args[2] as int?);
          assert(arg_transactionId != null,
              'Argument for dev.flutter.pigeon.firebase_firestore_webos.FirestoreFlutterApi.onTransactionCallback was null, expected non-null int.');
          try {
            api.onTransactionCallback(arg_appName!, arg_databaseId!, arg_transactionId!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
  }
}
