name: firebase_analytics_webos
description: webOS implementation of the firebase_analytics plugin.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.6.1
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  firebase_core: ^3.0.0
  path_provider: ^2.1.5
  path_provider_webos:
    git:
      url: https://github.com/lg-flutter-webos/plugins.git
      path: packages/path_provider
      ref: main
  firebase_analytics_platform_interface: any
  uuid: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      webos:
        dartPluginClass: FirebaseAnalyticsWebos
        pluginClass: FirebaseAnalyticsWebosPlugin
