// Autogenerated from Pigeon (v17.3.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#ifndef PIGEON_MESSAGES_G_H_
#define PIGEON_MESSAGES_G_H_
#include <flutter/basic_message_channel.h>
#include <flutter/binary_messenger.h>
#include <flutter/encodable_value.h>
#include <flutter/standard_message_codec.h>

#include <map>
#include <optional>
#include <string>

namespace firebase_firestore_webos {


// Generated class from Pigeon.

class FlutterError {
 public:
  explicit FlutterError(const std::string& code)
    : code_(code) {}
  explicit FlutterError(const std::string& code, const std::string& message)
    : code_(code), message_(message) {}
  explicit FlutterError(const std::string& code, const std::string& message, const flutter::EncodableValue& details)
    : code_(code), message_(message), details_(details) {}

  const std::string& code() const { return code_; }
  const std::string& message() const { return message_; }
  const flutter::EncodableValue& details() const { return details_; }

 private:
  std::string code_;
  std::string message_;
  flutter::EncodableValue details_;
};

template<class T> class ErrorOr {
 public:
  ErrorOr(const T& rhs) : v_(rhs) {}
  ErrorOr(const T&& rhs) : v_(std::move(rhs)) {}
  ErrorOr(const FlutterError& rhs) : v_(rhs) {}
  ErrorOr(const FlutterError&& rhs) : v_(std::move(rhs)) {}

  bool has_error() const { return std::holds_alternative<FlutterError>(v_); }
  const T& value() const { return std::get<T>(v_); };
  const FlutterError& error() const { return std::get<FlutterError>(v_); };

 private:
  friend class FirestoreHostApi;
  friend class FirestoreFlutterApi;
  ErrorOr() = default;
  T TakeValue() && { return std::get<T>(std::move(v_)); }

  std::variant<T, FlutterError> v_;
};


// Document change type
enum class PigeonDocumentChangeType {
  added = 0,
  modified = 1,
  removed = 2
};

enum class PigeonTransactionResult {
  success = 0,
  failure = 1
};

// Firestore settings configuration
//
// Generated class from Pigeon that represents data sent in messages.
class PigeonFirestoreSettings {
 public:
  // Constructs an object setting all fields.
  explicit PigeonFirestoreSettings(
    const std::string& host,
    bool ssl_enabled,
    bool persistence_enabled,
    int64_t cache_size_bytes);

  const std::string& host() const;
  void set_host(std::string_view value_arg);

  bool ssl_enabled() const;
  void set_ssl_enabled(bool value_arg);

  bool persistence_enabled() const;
  void set_persistence_enabled(bool value_arg);

  int64_t cache_size_bytes() const;
  void set_cache_size_bytes(int64_t value_arg);


 private:
  static PigeonFirestoreSettings FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class FirestoreHostApi;
  friend class FirestoreHostApiCodecSerializer;
  friend class FirestoreFlutterApi;
  friend class FirestoreFlutterApiCodecSerializer;
  std::string host_;
  bool ssl_enabled_;
  bool persistence_enabled_;
  int64_t cache_size_bytes_;

};


// Snapshot metadata
//
// Generated class from Pigeon that represents data sent in messages.
class PigeonSnapshotMetadata {
 public:
  // Constructs an object setting all fields.
  explicit PigeonSnapshotMetadata(
    bool has_pending_writes,
    bool is_from_cache);

  bool has_pending_writes() const;
  void set_has_pending_writes(bool value_arg);

  bool is_from_cache() const;
  void set_is_from_cache(bool value_arg);


 private:
  static PigeonSnapshotMetadata FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class PigeonDocumentSnapshot;
  friend class PigeonQuerySnapshot;
  friend class FirestoreHostApi;
  friend class FirestoreHostApiCodecSerializer;
  friend class FirestoreFlutterApi;
  friend class FirestoreFlutterApiCodecSerializer;
  bool has_pending_writes_;
  bool is_from_cache_;

};


// Document snapshot data
//
// Generated class from Pigeon that represents data sent in messages.
class PigeonDocumentSnapshot {
 public:
  // Constructs an object setting all non-nullable fields.
  explicit PigeonDocumentSnapshot(
    const std::string& path,
    const PigeonSnapshotMetadata& metadata,
    bool exists);

  // Constructs an object setting all fields.
  explicit PigeonDocumentSnapshot(
    const std::string& path,
    const flutter::EncodableMap* data,
    const PigeonSnapshotMetadata& metadata,
    bool exists);

  ~PigeonDocumentSnapshot() = default;
  PigeonDocumentSnapshot(const PigeonDocumentSnapshot& other);
  PigeonDocumentSnapshot& operator=(const PigeonDocumentSnapshot& other);
  PigeonDocumentSnapshot(PigeonDocumentSnapshot&& other) = default;
  PigeonDocumentSnapshot& operator=(PigeonDocumentSnapshot&& other) noexcept = default;
  const std::string& path() const;
  void set_path(std::string_view value_arg);

  const flutter::EncodableMap* data() const;
  void set_data(const flutter::EncodableMap* value_arg);
  void set_data(const flutter::EncodableMap& value_arg);

  const PigeonSnapshotMetadata& metadata() const;
  void set_metadata(const PigeonSnapshotMetadata& value_arg);

  bool exists() const;
  void set_exists(bool value_arg);


 private:
  static PigeonDocumentSnapshot FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class PigeonDocumentChange;
  friend class FirestoreHostApi;
  friend class FirestoreHostApiCodecSerializer;
  friend class FirestoreFlutterApi;
  friend class FirestoreFlutterApiCodecSerializer;
  std::string path_;
  std::optional<flutter::EncodableMap> data_;
  std::unique_ptr<PigeonSnapshotMetadata> metadata_;
  bool exists_;

};


// Document change
//
// Generated class from Pigeon that represents data sent in messages.
class PigeonDocumentChange {
 public:
  // Constructs an object setting all fields.
  explicit PigeonDocumentChange(
    const PigeonDocumentChangeType& type,
    const PigeonDocumentSnapshot& document,
    int64_t old_index,
    int64_t new_index);

  ~PigeonDocumentChange() = default;
  PigeonDocumentChange(const PigeonDocumentChange& other);
  PigeonDocumentChange& operator=(const PigeonDocumentChange& other);
  PigeonDocumentChange(PigeonDocumentChange&& other) = default;
  PigeonDocumentChange& operator=(PigeonDocumentChange&& other) noexcept = default;
  const PigeonDocumentChangeType& type() const;
  void set_type(const PigeonDocumentChangeType& value_arg);

  const PigeonDocumentSnapshot& document() const;
  void set_document(const PigeonDocumentSnapshot& value_arg);

  int64_t old_index() const;
  void set_old_index(int64_t value_arg);

  int64_t new_index() const;
  void set_new_index(int64_t value_arg);


 private:
  static PigeonDocumentChange FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class FirestoreHostApi;
  friend class FirestoreHostApiCodecSerializer;
  friend class FirestoreFlutterApi;
  friend class FirestoreFlutterApiCodecSerializer;
  PigeonDocumentChangeType type_;
  std::unique_ptr<PigeonDocumentSnapshot> document_;
  int64_t old_index_;
  int64_t new_index_;

};


// Query snapshot
//
// Generated class from Pigeon that represents data sent in messages.
class PigeonQuerySnapshot {
 public:
  // Constructs an object setting all fields.
  explicit PigeonQuerySnapshot(
    const flutter::EncodableList& documents,
    const flutter::EncodableList& document_changes,
    const PigeonSnapshotMetadata& metadata);

  ~PigeonQuerySnapshot() = default;
  PigeonQuerySnapshot(const PigeonQuerySnapshot& other);
  PigeonQuerySnapshot& operator=(const PigeonQuerySnapshot& other);
  PigeonQuerySnapshot(PigeonQuerySnapshot&& other) = default;
  PigeonQuerySnapshot& operator=(PigeonQuerySnapshot&& other) noexcept = default;
  const flutter::EncodableList& documents() const;
  void set_documents(const flutter::EncodableList& value_arg);

  const flutter::EncodableList& document_changes() const;
  void set_document_changes(const flutter::EncodableList& value_arg);

  const PigeonSnapshotMetadata& metadata() const;
  void set_metadata(const PigeonSnapshotMetadata& value_arg);


 private:
  static PigeonQuerySnapshot FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class FirestoreHostApi;
  friend class FirestoreHostApiCodecSerializer;
  friend class FirestoreFlutterApi;
  friend class FirestoreFlutterApiCodecSerializer;
  flutter::EncodableList documents_;
  flutter::EncodableList document_changes_;
  std::unique_ptr<PigeonSnapshotMetadata> metadata_;

};


// Get options
//
// Generated class from Pigeon that represents data sent in messages.
class PigeonGetOptions {
 public:
  // Constructs an object setting all fields.
  explicit PigeonGetOptions(const std::string& source);

  const std::string& source() const;
  void set_source(std::string_view value_arg);


 private:
  static PigeonGetOptions FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class FirestoreHostApi;
  friend class FirestoreHostApiCodecSerializer;
  friend class FirestoreFlutterApi;
  friend class FirestoreFlutterApiCodecSerializer;
  std::string source_;

};


// Set options
//
// Generated class from Pigeon that represents data sent in messages.
class PigeonSetOptions {
 public:
  // Constructs an object setting all non-nullable fields.
  explicit PigeonSetOptions(bool merge);

  // Constructs an object setting all fields.
  explicit PigeonSetOptions(
    bool merge,
    const flutter::EncodableList* merge_fields);

  bool merge() const;
  void set_merge(bool value_arg);

  const flutter::EncodableList* merge_fields() const;
  void set_merge_fields(const flutter::EncodableList* value_arg);
  void set_merge_fields(const flutter::EncodableList& value_arg);


 private:
  static PigeonSetOptions FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class FirestoreHostApi;
  friend class FirestoreHostApiCodecSerializer;
  friend class FirestoreFlutterApi;
  friend class FirestoreFlutterApiCodecSerializer;
  bool merge_;
  std::optional<flutter::EncodableList> merge_fields_;

};


// Transaction update data
//
// Generated class from Pigeon that represents data sent in messages.
class PigeonTransactionUpdate {
 public:
  // Constructs an object setting all non-nullable fields.
  explicit PigeonTransactionUpdate(
    const std::string& type,
    const std::string& path);

  // Constructs an object setting all fields.
  explicit PigeonTransactionUpdate(
    const std::string& type,
    const std::string& path,
    const flutter::EncodableMap* data);

  const std::string& type() const;
  void set_type(std::string_view value_arg);

  const std::string& path() const;
  void set_path(std::string_view value_arg);

  const flutter::EncodableMap* data() const;
  void set_data(const flutter::EncodableMap* value_arg);
  void set_data(const flutter::EncodableMap& value_arg);


 private:
  static PigeonTransactionUpdate FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class FirestoreHostApi;
  friend class FirestoreHostApiCodecSerializer;
  friend class FirestoreFlutterApi;
  friend class FirestoreFlutterApiCodecSerializer;
  std::string type_;
  std::string path_;
  std::optional<flutter::EncodableMap> data_;

};


// Aggregate query result
//
// Generated class from Pigeon that represents data sent in messages.
class PigeonAggregateQuerySnapshot {
 public:
  // Constructs an object setting all non-nullable fields.
  explicit PigeonAggregateQuerySnapshot(int64_t count);

  // Constructs an object setting all fields.
  explicit PigeonAggregateQuerySnapshot(
    int64_t count,
    const flutter::EncodableList* sum,
    const flutter::EncodableList* average);

  int64_t count() const;
  void set_count(int64_t value_arg);

  // Sum aggregation results: list of {field: string, value: double}
  const flutter::EncodableList* sum() const;
  void set_sum(const flutter::EncodableList* value_arg);
  void set_sum(const flutter::EncodableList& value_arg);

  // Average aggregation results: list of {field: string, value: double}
  const flutter::EncodableList* average() const;
  void set_average(const flutter::EncodableList* value_arg);
  void set_average(const flutter::EncodableList& value_arg);


 private:
  static PigeonAggregateQuerySnapshot FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class FirestoreHostApi;
  friend class FirestoreHostApiCodecSerializer;
  friend class FirestoreFlutterApi;
  friend class FirestoreFlutterApiCodecSerializer;
  int64_t count_;
  std::optional<flutter::EncodableList> sum_;
  std::optional<flutter::EncodableList> average_;

};


// A single aggregate result (field name + value)
//
// Generated class from Pigeon that represents data sent in messages.
class PigeonAggregateResult {
 public:
  // Constructs an object setting all fields.
  explicit PigeonAggregateResult(
    const std::string& field,
    double value);

  const std::string& field() const;
  void set_field(std::string_view value_arg);

  double value() const;
  void set_value(double value_arg);


 private:
  static PigeonAggregateResult FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class FirestoreHostApi;
  friend class FirestoreHostApiCodecSerializer;
  friend class FirestoreFlutterApi;
  friend class FirestoreFlutterApiCodecSerializer;
  std::string field_;
  double value_;

};


// Query parameters for building queries
//
// Generated class from Pigeon that represents data sent in messages.
class PigeonQueryParameters {
 public:
  // Constructs an object setting all non-nullable fields.
  PigeonQueryParameters();

  // Constructs an object setting all fields.
  explicit PigeonQueryParameters(
    const flutter::EncodableList* where,
    const flutter::EncodableList* order_by,
    const int64_t* limit,
    const int64_t* limit_to_last,
    const flutter::EncodableList* start_at,
    const flutter::EncodableList* start_after,
    const flutter::EncodableList* end_at,
    const flutter::EncodableList* end_before);

  const flutter::EncodableList* where() const;
  void set_where(const flutter::EncodableList* value_arg);
  void set_where(const flutter::EncodableList& value_arg);

  const flutter::EncodableList* order_by() const;
  void set_order_by(const flutter::EncodableList* value_arg);
  void set_order_by(const flutter::EncodableList& value_arg);

  const int64_t* limit() const;
  void set_limit(const int64_t* value_arg);
  void set_limit(int64_t value_arg);

  const int64_t* limit_to_last() const;
  void set_limit_to_last(const int64_t* value_arg);
  void set_limit_to_last(int64_t value_arg);

  const flutter::EncodableList* start_at() const;
  void set_start_at(const flutter::EncodableList* value_arg);
  void set_start_at(const flutter::EncodableList& value_arg);

  const flutter::EncodableList* start_after() const;
  void set_start_after(const flutter::EncodableList* value_arg);
  void set_start_after(const flutter::EncodableList& value_arg);

  const flutter::EncodableList* end_at() const;
  void set_end_at(const flutter::EncodableList* value_arg);
  void set_end_at(const flutter::EncodableList& value_arg);

  const flutter::EncodableList* end_before() const;
  void set_end_before(const flutter::EncodableList* value_arg);
  void set_end_before(const flutter::EncodableList& value_arg);


 private:
  static PigeonQueryParameters FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class FirestoreHostApi;
  friend class FirestoreHostApiCodecSerializer;
  friend class FirestoreFlutterApi;
  friend class FirestoreFlutterApiCodecSerializer;
  std::optional<flutter::EncodableList> where_;
  std::optional<flutter::EncodableList> order_by_;
  std::optional<int64_t> limit_;
  std::optional<int64_t> limit_to_last_;
  std::optional<flutter::EncodableList> start_at_;
  std::optional<flutter::EncodableList> start_after_;
  std::optional<flutter::EncodableList> end_at_;
  std::optional<flutter::EncodableList> end_before_;

};


// Query filter
//
// Generated class from Pigeon that represents data sent in messages.
class PigeonQueryFilter {
 public:
  // Constructs an object setting all non-nullable fields.
  explicit PigeonQueryFilter(
    const std::string& field,
    const std::string& op);

  // Constructs an object setting all fields.
  explicit PigeonQueryFilter(
    const std::string& field,
    const std::string& op,
    const flutter::EncodableValue* value);

  const std::string& field() const;
  void set_field(std::string_view value_arg);

  const std::string& op() const;
  void set_op(std::string_view value_arg);

  const flutter::EncodableValue* value() const;
  void set_value(const flutter::EncodableValue* value_arg);
  void set_value(const flutter::EncodableValue& value_arg);


 private:
  static PigeonQueryFilter FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class FirestoreHostApi;
  friend class FirestoreHostApiCodecSerializer;
  friend class FirestoreFlutterApi;
  friend class FirestoreFlutterApiCodecSerializer;
  std::string field_;
  std::string op_;
  std::optional<flutter::EncodableValue> value_;

};


// Query order
//
// Generated class from Pigeon that represents data sent in messages.
class PigeonQueryOrder {
 public:
  // Constructs an object setting all fields.
  explicit PigeonQueryOrder(
    const std::string& field,
    bool descending);

  const std::string& field() const;
  void set_field(std::string_view value_arg);

  bool descending() const;
  void set_descending(bool value_arg);


 private:
  static PigeonQueryOrder FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class FirestoreHostApi;
  friend class FirestoreHostApiCodecSerializer;
  friend class FirestoreFlutterApi;
  friend class FirestoreFlutterApiCodecSerializer;
  std::string field_;
  bool descending_;

};

class FirestoreHostApiCodecSerializer : public flutter::StandardCodecSerializer {
 public:
  FirestoreHostApiCodecSerializer();
  inline static FirestoreHostApiCodecSerializer& GetInstance() {
    static FirestoreHostApiCodecSerializer sInstance;
    return sInstance;
  }

  void WriteValue(
    const flutter::EncodableValue& value,
    flutter::ByteStreamWriter* stream) const override;

 protected:
  flutter::EncodableValue ReadValueOfType(
    uint8_t type,
    flutter::ByteStreamReader* stream) const override;

};

// Generated interface from Pigeon that represents a handler of messages from Flutter.
class FirestoreHostApi {
 public:
  FirestoreHostApi(const FirestoreHostApi&) = delete;
  FirestoreHostApi& operator=(const FirestoreHostApi&) = delete;
  virtual ~FirestoreHostApi() {}
  // Initialize Firestore instance
  virtual void InitializeFirestore(
    const std::string& app_name,
    const std::string& database_id,
    std::function<void(std::optional<FlutterError> reply)> result) = 0;
  // Set Firestore settings (must be called before any other operation)
  virtual void SetSettings(
    const std::string& app_name,
    const std::string& database_id,
    const PigeonFirestoreSettings& settings,
    std::function<void(std::optional<FlutterError> reply)> result) = 0;
  // Enable network
  virtual void EnableNetwork(
    const std::string& app_name,
    const std::string& database_id,
    std::function<void(std::optional<FlutterError> reply)> result) = 0;
  // Disable network
  virtual void DisableNetwork(
    const std::string& app_name,
    const std::string& database_id,
    std::function<void(std::optional<FlutterError> reply)> result) = 0;
  // Clear persistence
  virtual void ClearPersistence(
    const std::string& app_name,
    const std::string& database_id,
    std::function<void(std::optional<FlutterError> reply)> result) = 0;
  // Terminate Firestore instance
  virtual void Terminate(
    const std::string& app_name,
    const std::string& database_id,
    std::function<void(std::optional<FlutterError> reply)> result) = 0;
  // Wait for pending writes
  virtual void WaitForPendingWrites(
    const std::string& app_name,
    const std::string& database_id,
    std::function<void(std::optional<FlutterError> reply)> result) = 0;
  // Get a document
  virtual void DocumentGet(
    const std::string& app_name,
    const std::string& database_id,
    const std::string& path,
    const PigeonGetOptions& options,
    std::function<void(ErrorOr<PigeonDocumentSnapshot> reply)> result) = 0;
  // Set a document
  virtual void DocumentSet(
    const std::string& app_name,
    const std::string& database_id,
    const std::string& path,
    const flutter::EncodableMap& data,
    const PigeonSetOptions& options,
    std::function<void(std::optional<FlutterError> reply)> result) = 0;
  // Update a document
  virtual void DocumentUpdate(
    const std::string& app_name,
    const std::string& database_id,
    const std::string& path,
    const flutter::EncodableMap& data,
    std::function<void(std::optional<FlutterError> reply)> result) = 0;
  // Delete a document
  virtual void DocumentDelete(
    const std::string& app_name,
    const std::string& database_id,
    const std::string& path,
    std::function<void(std::optional<FlutterError> reply)> result) = 0;
  // Start listening to a document
  virtual void DocumentAddSnapshotListener(
    const std::string& app_name,
    const std::string& database_id,
    const std::string& path,
    bool include_metadata_changes,
    std::function<void(ErrorOr<int64_t> reply)> result) = 0;
  // Query get
  virtual void QueryGet(
    const std::string& app_name,
    const std::string& database_id,
    const std::string& path,
    bool is_collection_group,
    const PigeonQueryParameters& parameters,
    const PigeonGetOptions& options,
    std::function<void(ErrorOr<PigeonQuerySnapshot> reply)> result) = 0;
  // Start listening to a query
  virtual void QueryAddSnapshotListener(
    const std::string& app_name,
    const std::string& database_id,
    const std::string& path,
    bool is_collection_group,
    const PigeonQueryParameters& parameters,
    bool include_metadata_changes,
    std::function<void(ErrorOr<int64_t> reply)> result) = 0;
  // Count aggregate query
  virtual void QueryCount(
    const std::string& app_name,
    const std::string& database_id,
    const std::string& path,
    bool is_collection_group,
    const PigeonQueryParameters& parameters,
    std::function<void(ErrorOr<PigeonAggregateQuerySnapshot> reply)> result) = 0;
  // Aggregate query (supports count, sum, average)
  // The aggregateTypes parameter is a list of strings: "count", "sum:fieldName", "avg:fieldName"
  virtual void QueryAggregate(
    const std::string& app_name,
    const std::string& database_id,
    const std::string& path,
    bool is_collection_group,
    const PigeonQueryParameters& parameters,
    const flutter::EncodableList& aggregate_types,
    std::function<void(ErrorOr<PigeonAggregateQuerySnapshot> reply)> result) = 0;
  // Remove a snapshot listener
  virtual void RemoveSnapshotListener(
    const std::string& app_name,
    const std::string& database_id,
    int64_t listener_id,
    std::function<void(std::optional<FlutterError> reply)> result) = 0;
  // Use emulator
  virtual void UseEmulator(
    const std::string& app_name,
    const std::string& database_id,
    const std::string& host,
    int64_t port,
    std::function<void(std::optional<FlutterError> reply)> result) = 0;
  // Set logging enabled
  virtual void SetLoggingEnabled(
    const std::string& app_name,
    const std::string& database_id,
    bool enabled,
    std::function<void(std::optional<FlutterError> reply)> result) = 0;
  // Commit a batch write
  virtual void BatchCommit(
    const std::string& app_name,
    const std::string& database_id,
    const flutter::EncodableList& writes,
    std::function<void(std::optional<FlutterError> reply)> result) = 0;
  // Run a transaction
  virtual void RunTransaction(
    const std::string& app_name,
    const std::string& database_id,
    int64_t transaction_id,
    int64_t max_attempts,
    std::function<void(std::optional<FlutterError> reply)> result) = 0;
  // Get document in transaction
  virtual void TransactionGet(
    const std::string& app_name,
    const std::string& database_id,
    int64_t transaction_id,
    const std::string& path,
    std::function<void(ErrorOr<PigeonDocumentSnapshot> reply)> result) = 0;
  // Complete transaction with updates
  virtual void TransactionComplete(
    const std::string& app_name,
    const std::string& database_id,
    int64_t transaction_id,
    const PigeonTransactionResult& result_type,
    const flutter::EncodableList* updates,
    std::function<void(std::optional<FlutterError> reply)> result) = 0;

  // The codec used by FirestoreHostApi.
  static const flutter::StandardMessageCodec& GetCodec();
  // Sets up an instance of `FirestoreHostApi` to handle messages through the `binary_messenger`.
  static void SetUp(
    flutter::BinaryMessenger* binary_messenger,
    FirestoreHostApi* api);
  static flutter::EncodableValue WrapError(std::string_view error_message);
  static flutter::EncodableValue WrapError(const FlutterError& error);

 protected:
  FirestoreHostApi() = default;

};
// Generated class from Pigeon that represents Flutter messages that can be called from C++.
class FirestoreFlutterApi {
 public:
  FirestoreFlutterApi(flutter::BinaryMessenger* binary_messenger);
  static const flutter::StandardMessageCodec& GetCodec();
  // Request transaction updates from Dart
  // Returns JSON-encoded result data or error
  void OnTransactionCallback(
    const std::string& app_name,
    const std::string& database_id,
    int64_t transaction_id,
    std::function<void(void)>&& on_success,
    std::function<void(const FlutterError&)>&& on_error);

 private:
  flutter::BinaryMessenger* binary_messenger_;
};

}  // namespace firebase_firestore_webos
#endif  // PIGEON_MESSAGES_G_H_
