// Autogenerated from Pigeon (v17.3.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#undef _HAS_EXCEPTIONS

#include "messages.g.h"

#include <flutter/basic_message_channel.h>
#include <flutter/binary_messenger.h>
#include <flutter/encodable_value.h>
#include <flutter/standard_message_codec.h>

#include <map>
#include <optional>
#include <string>

namespace firebase_firestore_webos {
using flutter::BasicMessageChannel;
using flutter::CustomEncodableValue;
using flutter::EncodableList;
using flutter::EncodableMap;
using flutter::EncodableValue;

FlutterError CreateConnectionError(const std::string channel_name) {
    return FlutterError(
        "channel-error",
        "Unable to establish connection on channel: '" + channel_name + "'.",
        EncodableValue(""));
}

// PigeonFirestoreSettings

PigeonFirestoreSettings::PigeonFirestoreSettings(
  const std::string& host,
  bool ssl_enabled,
  bool persistence_enabled,
  int64_t cache_size_bytes)
 : host_(host),
    ssl_enabled_(ssl_enabled),
    persistence_enabled_(persistence_enabled),
    cache_size_bytes_(cache_size_bytes) {}

const std::string& PigeonFirestoreSettings::host() const {
  return host_;
}

void PigeonFirestoreSettings::set_host(std::string_view value_arg) {
  host_ = value_arg;
}


bool PigeonFirestoreSettings::ssl_enabled() const {
  return ssl_enabled_;
}

void PigeonFirestoreSettings::set_ssl_enabled(bool value_arg) {
  ssl_enabled_ = value_arg;
}


bool PigeonFirestoreSettings::persistence_enabled() const {
  return persistence_enabled_;
}

void PigeonFirestoreSettings::set_persistence_enabled(bool value_arg) {
  persistence_enabled_ = value_arg;
}


int64_t PigeonFirestoreSettings::cache_size_bytes() const {
  return cache_size_bytes_;
}

void PigeonFirestoreSettings::set_cache_size_bytes(int64_t value_arg) {
  cache_size_bytes_ = value_arg;
}


EncodableList PigeonFirestoreSettings::ToEncodableList() const {
  EncodableList list;
  list.reserve(4);
  list.push_back(EncodableValue(host_));
  list.push_back(EncodableValue(ssl_enabled_));
  list.push_back(EncodableValue(persistence_enabled_));
  list.push_back(EncodableValue(cache_size_bytes_));
  return list;
}

PigeonFirestoreSettings PigeonFirestoreSettings::FromEncodableList(const EncodableList& list) {
  PigeonFirestoreSettings decoded(
    std::get<std::string>(list[0]),
    std::get<bool>(list[1]),
    std::get<bool>(list[2]),
    list[3].LongValue());
  return decoded;
}

// PigeonSnapshotMetadata

PigeonSnapshotMetadata::PigeonSnapshotMetadata(
  bool has_pending_writes,
  bool is_from_cache)
 : has_pending_writes_(has_pending_writes),
    is_from_cache_(is_from_cache) {}

bool PigeonSnapshotMetadata::has_pending_writes() const {
  return has_pending_writes_;
}

void PigeonSnapshotMetadata::set_has_pending_writes(bool value_arg) {
  has_pending_writes_ = value_arg;
}


bool PigeonSnapshotMetadata::is_from_cache() const {
  return is_from_cache_;
}

void PigeonSnapshotMetadata::set_is_from_cache(bool value_arg) {
  is_from_cache_ = value_arg;
}


EncodableList PigeonSnapshotMetadata::ToEncodableList() const {
  EncodableList list;
  list.reserve(2);
  list.push_back(EncodableValue(has_pending_writes_));
  list.push_back(EncodableValue(is_from_cache_));
  return list;
}

PigeonSnapshotMetadata PigeonSnapshotMetadata::FromEncodableList(const EncodableList& list) {
  PigeonSnapshotMetadata decoded(
    std::get<bool>(list[0]),
    std::get<bool>(list[1]));
  return decoded;
}

// PigeonDocumentSnapshot

PigeonDocumentSnapshot::PigeonDocumentSnapshot(
  const std::string& path,
  const PigeonSnapshotMetadata& metadata,
  bool exists)
 : path_(path),
    metadata_(std::make_unique<PigeonSnapshotMetadata>(metadata)),
    exists_(exists) {}

PigeonDocumentSnapshot::PigeonDocumentSnapshot(
  const std::string& path,
  const EncodableMap* data,
  const PigeonSnapshotMetadata& metadata,
  bool exists)
 : path_(path),
    data_(data ? std::optional<EncodableMap>(*data) : std::nullopt),
    metadata_(std::make_unique<PigeonSnapshotMetadata>(metadata)),
    exists_(exists) {}

PigeonDocumentSnapshot::PigeonDocumentSnapshot(const PigeonDocumentSnapshot& other)
 : path_(other.path_),
    data_(other.data_ ? std::optional<EncodableMap>(*other.data_) : std::nullopt),
    metadata_(std::make_unique<PigeonSnapshotMetadata>(*other.metadata_)),
    exists_(other.exists_) {}

PigeonDocumentSnapshot& PigeonDocumentSnapshot::operator=(const PigeonDocumentSnapshot& other) {
  path_ = other.path_;
  data_ = other.data_;
  metadata_ = std::make_unique<PigeonSnapshotMetadata>(*other.metadata_);
  exists_ = other.exists_;
  return *this;
}

const std::string& PigeonDocumentSnapshot::path() const {
  return path_;
}

void PigeonDocumentSnapshot::set_path(std::string_view value_arg) {
  path_ = value_arg;
}


const EncodableMap* PigeonDocumentSnapshot::data() const {
  return data_ ? &(*data_) : nullptr;
}

void PigeonDocumentSnapshot::set_data(const EncodableMap* value_arg) {
  data_ = value_arg ? std::optional<EncodableMap>(*value_arg) : std::nullopt;
}

void PigeonDocumentSnapshot::set_data(const EncodableMap& value_arg) {
  data_ = value_arg;
}


const PigeonSnapshotMetadata& PigeonDocumentSnapshot::metadata() const {
  return *metadata_;
}

void PigeonDocumentSnapshot::set_metadata(const PigeonSnapshotMetadata& value_arg) {
  metadata_ = std::make_unique<PigeonSnapshotMetadata>(value_arg);
}


bool PigeonDocumentSnapshot::exists() const {
  return exists_;
}

void PigeonDocumentSnapshot::set_exists(bool value_arg) {
  exists_ = value_arg;
}


EncodableList PigeonDocumentSnapshot::ToEncodableList() const {
  EncodableList list;
  list.reserve(4);
  list.push_back(EncodableValue(path_));
  list.push_back(data_ ? EncodableValue(*data_) : EncodableValue());
  list.push_back(EncodableValue(metadata_->ToEncodableList()));
  list.push_back(EncodableValue(exists_));
  return list;
}

PigeonDocumentSnapshot PigeonDocumentSnapshot::FromEncodableList(const EncodableList& list) {
  PigeonDocumentSnapshot decoded(
    std::get<std::string>(list[0]),
    PigeonSnapshotMetadata::FromEncodableList(std::get<EncodableList>(list[2])),
    std::get<bool>(list[3]));
  auto& encodable_data = list[1];
  if (!encodable_data.IsNull()) {
    decoded.set_data(std::get<EncodableMap>(encodable_data));
  }
  return decoded;
}

// PigeonDocumentChange

PigeonDocumentChange::PigeonDocumentChange(
  const PigeonDocumentChangeType& type,
  const PigeonDocumentSnapshot& document,
  int64_t old_index,
  int64_t new_index)
 : type_(type),
    document_(std::make_unique<PigeonDocumentSnapshot>(document)),
    old_index_(old_index),
    new_index_(new_index) {}

PigeonDocumentChange::PigeonDocumentChange(const PigeonDocumentChange& other)
 : type_(other.type_),
    document_(std::make_unique<PigeonDocumentSnapshot>(*other.document_)),
    old_index_(other.old_index_),
    new_index_(other.new_index_) {}

PigeonDocumentChange& PigeonDocumentChange::operator=(const PigeonDocumentChange& other) {
  type_ = other.type_;
  document_ = std::make_unique<PigeonDocumentSnapshot>(*other.document_);
  old_index_ = other.old_index_;
  new_index_ = other.new_index_;
  return *this;
}

const PigeonDocumentChangeType& PigeonDocumentChange::type() const {
  return type_;
}

void PigeonDocumentChange::set_type(const PigeonDocumentChangeType& value_arg) {
  type_ = value_arg;
}


const PigeonDocumentSnapshot& PigeonDocumentChange::document() const {
  return *document_;
}

void PigeonDocumentChange::set_document(const PigeonDocumentSnapshot& value_arg) {
  document_ = std::make_unique<PigeonDocumentSnapshot>(value_arg);
}


int64_t PigeonDocumentChange::old_index() const {
  return old_index_;
}

void PigeonDocumentChange::set_old_index(int64_t value_arg) {
  old_index_ = value_arg;
}


int64_t PigeonDocumentChange::new_index() const {
  return new_index_;
}

void PigeonDocumentChange::set_new_index(int64_t value_arg) {
  new_index_ = value_arg;
}


EncodableList PigeonDocumentChange::ToEncodableList() const {
  EncodableList list;
  list.reserve(4);
  list.push_back(EncodableValue((int)type_));
  list.push_back(EncodableValue(document_->ToEncodableList()));
  list.push_back(EncodableValue(old_index_));
  list.push_back(EncodableValue(new_index_));
  return list;
}

PigeonDocumentChange PigeonDocumentChange::FromEncodableList(const EncodableList& list) {
  PigeonDocumentChange decoded(
    (PigeonDocumentChangeType)(std::get<int32_t>(list[0])),
    PigeonDocumentSnapshot::FromEncodableList(std::get<EncodableList>(list[1])),
    list[2].LongValue(),
    list[3].LongValue());
  return decoded;
}

// PigeonQuerySnapshot

PigeonQuerySnapshot::PigeonQuerySnapshot(
  const EncodableList& documents,
  const EncodableList& document_changes,
  const PigeonSnapshotMetadata& metadata)
 : documents_(documents),
    document_changes_(document_changes),
    metadata_(std::make_unique<PigeonSnapshotMetadata>(metadata)) {}

PigeonQuerySnapshot::PigeonQuerySnapshot(const PigeonQuerySnapshot& other)
 : documents_(other.documents_),
    document_changes_(other.document_changes_),
    metadata_(std::make_unique<PigeonSnapshotMetadata>(*other.metadata_)) {}

PigeonQuerySnapshot& PigeonQuerySnapshot::operator=(const PigeonQuerySnapshot& other) {
  documents_ = other.documents_;
  document_changes_ = other.document_changes_;
  metadata_ = std::make_unique<PigeonSnapshotMetadata>(*other.metadata_);
  return *this;
}

const EncodableList& PigeonQuerySnapshot::documents() const {
  return documents_;
}

void PigeonQuerySnapshot::set_documents(const EncodableList& value_arg) {
  documents_ = value_arg;
}


const EncodableList& PigeonQuerySnapshot::document_changes() const {
  return document_changes_;
}

void PigeonQuerySnapshot::set_document_changes(const EncodableList& value_arg) {
  document_changes_ = value_arg;
}


const PigeonSnapshotMetadata& PigeonQuerySnapshot::metadata() const {
  return *metadata_;
}

void PigeonQuerySnapshot::set_metadata(const PigeonSnapshotMetadata& value_arg) {
  metadata_ = std::make_unique<PigeonSnapshotMetadata>(value_arg);
}


EncodableList PigeonQuerySnapshot::ToEncodableList() const {
  EncodableList list;
  list.reserve(3);
  list.push_back(EncodableValue(documents_));
  list.push_back(EncodableValue(document_changes_));
  list.push_back(EncodableValue(metadata_->ToEncodableList()));
  return list;
}

PigeonQuerySnapshot PigeonQuerySnapshot::FromEncodableList(const EncodableList& list) {
  PigeonQuerySnapshot decoded(
    std::get<EncodableList>(list[0]),
    std::get<EncodableList>(list[1]),
    PigeonSnapshotMetadata::FromEncodableList(std::get<EncodableList>(list[2])));
  return decoded;
}

// PigeonGetOptions

PigeonGetOptions::PigeonGetOptions(const std::string& source)
 : source_(source) {}

const std::string& PigeonGetOptions::source() const {
  return source_;
}

void PigeonGetOptions::set_source(std::string_view value_arg) {
  source_ = value_arg;
}


EncodableList PigeonGetOptions::ToEncodableList() const {
  EncodableList list;
  list.reserve(1);
  list.push_back(EncodableValue(source_));
  return list;
}

PigeonGetOptions PigeonGetOptions::FromEncodableList(const EncodableList& list) {
  PigeonGetOptions decoded(
    std::get<std::string>(list[0]));
  return decoded;
}

// PigeonSetOptions

PigeonSetOptions::PigeonSetOptions(bool merge)
 : merge_(merge) {}

PigeonSetOptions::PigeonSetOptions(
  bool merge,
  const EncodableList* merge_fields)
 : merge_(merge),
    merge_fields_(merge_fields ? std::optional<EncodableList>(*merge_fields) : std::nullopt) {}

bool PigeonSetOptions::merge() const {
  return merge_;
}

void PigeonSetOptions::set_merge(bool value_arg) {
  merge_ = value_arg;
}


const EncodableList* PigeonSetOptions::merge_fields() const {
  return merge_fields_ ? &(*merge_fields_) : nullptr;
}

void PigeonSetOptions::set_merge_fields(const EncodableList* value_arg) {
  merge_fields_ = value_arg ? std::optional<EncodableList>(*value_arg) : std::nullopt;
}

void PigeonSetOptions::set_merge_fields(const EncodableList& value_arg) {
  merge_fields_ = value_arg;
}


EncodableList PigeonSetOptions::ToEncodableList() const {
  EncodableList list;
  list.reserve(2);
  list.push_back(EncodableValue(merge_));
  list.push_back(merge_fields_ ? EncodableValue(*merge_fields_) : EncodableValue());
  return list;
}

PigeonSetOptions PigeonSetOptions::FromEncodableList(const EncodableList& list) {
  PigeonSetOptions decoded(
    std::get<bool>(list[0]));
  auto& encodable_merge_fields = list[1];
  if (!encodable_merge_fields.IsNull()) {
    decoded.set_merge_fields(std::get<EncodableList>(encodable_merge_fields));
  }
  return decoded;
}

// PigeonTransactionUpdate

PigeonTransactionUpdate::PigeonTransactionUpdate(
  const std::string& type,
  const std::string& path)
 : type_(type),
    path_(path) {}

PigeonTransactionUpdate::PigeonTransactionUpdate(
  const std::string& type,
  const std::string& path,
  const EncodableMap* data)
 : type_(type),
    path_(path),
    data_(data ? std::optional<EncodableMap>(*data) : std::nullopt) {}

const std::string& PigeonTransactionUpdate::type() const {
  return type_;
}

void PigeonTransactionUpdate::set_type(std::string_view value_arg) {
  type_ = value_arg;
}


const std::string& PigeonTransactionUpdate::path() const {
  return path_;
}

void PigeonTransactionUpdate::set_path(std::string_view value_arg) {
  path_ = value_arg;
}


const EncodableMap* PigeonTransactionUpdate::data() const {
  return data_ ? &(*data_) : nullptr;
}

void PigeonTransactionUpdate::set_data(const EncodableMap* value_arg) {
  data_ = value_arg ? std::optional<EncodableMap>(*value_arg) : std::nullopt;
}

void PigeonTransactionUpdate::set_data(const EncodableMap& value_arg) {
  data_ = value_arg;
}


EncodableList PigeonTransactionUpdate::ToEncodableList() const {
  EncodableList list;
  list.reserve(3);
  list.push_back(EncodableValue(type_));
  list.push_back(EncodableValue(path_));
  list.push_back(data_ ? EncodableValue(*data_) : EncodableValue());
  return list;
}

PigeonTransactionUpdate PigeonTransactionUpdate::FromEncodableList(const EncodableList& list) {
  PigeonTransactionUpdate decoded(
    std::get<std::string>(list[0]),
    std::get<std::string>(list[1]));
  auto& encodable_data = list[2];
  if (!encodable_data.IsNull()) {
    decoded.set_data(std::get<EncodableMap>(encodable_data));
  }
  return decoded;
}

// PigeonAggregateQuerySnapshot

PigeonAggregateQuerySnapshot::PigeonAggregateQuerySnapshot(int64_t count)
 : count_(count) {}

PigeonAggregateQuerySnapshot::PigeonAggregateQuerySnapshot(
  int64_t count,
  const EncodableList* sum,
  const EncodableList* average)
 : count_(count),
    sum_(sum ? std::optional<EncodableList>(*sum) : std::nullopt),
    average_(average ? std::optional<EncodableList>(*average) : std::nullopt) {}

int64_t PigeonAggregateQuerySnapshot::count() const {
  return count_;
}

void PigeonAggregateQuerySnapshot::set_count(int64_t value_arg) {
  count_ = value_arg;
}


const EncodableList* PigeonAggregateQuerySnapshot::sum() const {
  return sum_ ? &(*sum_) : nullptr;
}

void PigeonAggregateQuerySnapshot::set_sum(const EncodableList* value_arg) {
  sum_ = value_arg ? std::optional<EncodableList>(*value_arg) : std::nullopt;
}

void PigeonAggregateQuerySnapshot::set_sum(const EncodableList& value_arg) {
  sum_ = value_arg;
}


const EncodableList* PigeonAggregateQuerySnapshot::average() const {
  return average_ ? &(*average_) : nullptr;
}

void PigeonAggregateQuerySnapshot::set_average(const EncodableList* value_arg) {
  average_ = value_arg ? std::optional<EncodableList>(*value_arg) : std::nullopt;
}

void PigeonAggregateQuerySnapshot::set_average(const EncodableList& value_arg) {
  average_ = value_arg;
}


EncodableList PigeonAggregateQuerySnapshot::ToEncodableList() const {
  EncodableList list;
  list.reserve(3);
  list.push_back(EncodableValue(count_));
  list.push_back(sum_ ? EncodableValue(*sum_) : EncodableValue());
  list.push_back(average_ ? EncodableValue(*average_) : EncodableValue());
  return list;
}

PigeonAggregateQuerySnapshot PigeonAggregateQuerySnapshot::FromEncodableList(const EncodableList& list) {
  PigeonAggregateQuerySnapshot decoded(
    list[0].LongValue());
  auto& encodable_sum = list[1];
  if (!encodable_sum.IsNull()) {
    decoded.set_sum(std::get<EncodableList>(encodable_sum));
  }
  auto& encodable_average = list[2];
  if (!encodable_average.IsNull()) {
    decoded.set_average(std::get<EncodableList>(encodable_average));
  }
  return decoded;
}

// PigeonAggregateResult

PigeonAggregateResult::PigeonAggregateResult(
  const std::string& field,
  double value)
 : field_(field),
    value_(value) {}

const std::string& PigeonAggregateResult::field() const {
  return field_;
}

void PigeonAggregateResult::set_field(std::string_view value_arg) {
  field_ = value_arg;
}


double PigeonAggregateResult::value() const {
  return value_;
}

void PigeonAggregateResult::set_value(double value_arg) {
  value_ = value_arg;
}


EncodableList PigeonAggregateResult::ToEncodableList() const {
  EncodableList list;
  list.reserve(2);
  list.push_back(EncodableValue(field_));
  list.push_back(EncodableValue(value_));
  return list;
}

PigeonAggregateResult PigeonAggregateResult::FromEncodableList(const EncodableList& list) {
  PigeonAggregateResult decoded(
    std::get<std::string>(list[0]),
    std::get<double>(list[1]));
  return decoded;
}

// PigeonQueryParameters

PigeonQueryParameters::PigeonQueryParameters() {}

PigeonQueryParameters::PigeonQueryParameters(
  const EncodableList* where,
  const EncodableList* order_by,
  const int64_t* limit,
  const int64_t* limit_to_last,
  const EncodableList* start_at,
  const EncodableList* start_after,
  const EncodableList* end_at,
  const EncodableList* end_before)
 : where_(where ? std::optional<EncodableList>(*where) : std::nullopt),
    order_by_(order_by ? std::optional<EncodableList>(*order_by) : std::nullopt),
    limit_(limit ? std::optional<int64_t>(*limit) : std::nullopt),
    limit_to_last_(limit_to_last ? std::optional<int64_t>(*limit_to_last) : std::nullopt),
    start_at_(start_at ? std::optional<EncodableList>(*start_at) : std::nullopt),
    start_after_(start_after ? std::optional<EncodableList>(*start_after) : std::nullopt),
    end_at_(end_at ? std::optional<EncodableList>(*end_at) : std::nullopt),
    end_before_(end_before ? std::optional<EncodableList>(*end_before) : std::nullopt) {}

const EncodableList* PigeonQueryParameters::where() const {
  return where_ ? &(*where_) : nullptr;
}

void PigeonQueryParameters::set_where(const EncodableList* value_arg) {
  where_ = value_arg ? std::optional<EncodableList>(*value_arg) : std::nullopt;
}

void PigeonQueryParameters::set_where(const EncodableList& value_arg) {
  where_ = value_arg;
}


const EncodableList* PigeonQueryParameters::order_by() const {
  return order_by_ ? &(*order_by_) : nullptr;
}

void PigeonQueryParameters::set_order_by(const EncodableList* value_arg) {
  order_by_ = value_arg ? std::optional<EncodableList>(*value_arg) : std::nullopt;
}

void PigeonQueryParameters::set_order_by(const EncodableList& value_arg) {
  order_by_ = value_arg;
}


const int64_t* PigeonQueryParameters::limit() const {
  return limit_ ? &(*limit_) : nullptr;
}

void PigeonQueryParameters::set_limit(const int64_t* value_arg) {
  limit_ = value_arg ? std::optional<int64_t>(*value_arg) : std::nullopt;
}

void PigeonQueryParameters::set_limit(int64_t value_arg) {
  limit_ = value_arg;
}


const int64_t* PigeonQueryParameters::limit_to_last() const {
  return limit_to_last_ ? &(*limit_to_last_) : nullptr;
}

void PigeonQueryParameters::set_limit_to_last(const int64_t* value_arg) {
  limit_to_last_ = value_arg ? std::optional<int64_t>(*value_arg) : std::nullopt;
}

void PigeonQueryParameters::set_limit_to_last(int64_t value_arg) {
  limit_to_last_ = value_arg;
}


const EncodableList* PigeonQueryParameters::start_at() const {
  return start_at_ ? &(*start_at_) : nullptr;
}

void PigeonQueryParameters::set_start_at(const EncodableList* value_arg) {
  start_at_ = value_arg ? std::optional<EncodableList>(*value_arg) : std::nullopt;
}

void PigeonQueryParameters::set_start_at(const EncodableList& value_arg) {
  start_at_ = value_arg;
}


const EncodableList* PigeonQueryParameters::start_after() const {
  return start_after_ ? &(*start_after_) : nullptr;
}

void PigeonQueryParameters::set_start_after(const EncodableList* value_arg) {
  start_after_ = value_arg ? std::optional<EncodableList>(*value_arg) : std::nullopt;
}

void PigeonQueryParameters::set_start_after(const EncodableList& value_arg) {
  start_after_ = value_arg;
}


const EncodableList* PigeonQueryParameters::end_at() const {
  return end_at_ ? &(*end_at_) : nullptr;
}

void PigeonQueryParameters::set_end_at(const EncodableList* value_arg) {
  end_at_ = value_arg ? std::optional<EncodableList>(*value_arg) : std::nullopt;
}

void PigeonQueryParameters::set_end_at(const EncodableList& value_arg) {
  end_at_ = value_arg;
}


const EncodableList* PigeonQueryParameters::end_before() const {
  return end_before_ ? &(*end_before_) : nullptr;
}

void PigeonQueryParameters::set_end_before(const EncodableList* value_arg) {
  end_before_ = value_arg ? std::optional<EncodableList>(*value_arg) : std::nullopt;
}

void PigeonQueryParameters::set_end_before(const EncodableList& value_arg) {
  end_before_ = value_arg;
}


EncodableList PigeonQueryParameters::ToEncodableList() const {
  EncodableList list;
  list.reserve(8);
  list.push_back(where_ ? EncodableValue(*where_) : EncodableValue());
  list.push_back(order_by_ ? EncodableValue(*order_by_) : EncodableValue());
  list.push_back(limit_ ? EncodableValue(*limit_) : EncodableValue());
  list.push_back(limit_to_last_ ? EncodableValue(*limit_to_last_) : EncodableValue());
  list.push_back(start_at_ ? EncodableValue(*start_at_) : EncodableValue());
  list.push_back(start_after_ ? EncodableValue(*start_after_) : EncodableValue());
  list.push_back(end_at_ ? EncodableValue(*end_at_) : EncodableValue());
  list.push_back(end_before_ ? EncodableValue(*end_before_) : EncodableValue());
  return list;
}

PigeonQueryParameters PigeonQueryParameters::FromEncodableList(const EncodableList& list) {
  PigeonQueryParameters decoded;
  auto& encodable_where = list[0];
  if (!encodable_where.IsNull()) {
    decoded.set_where(std::get<EncodableList>(encodable_where));
  }
  auto& encodable_order_by = list[1];
  if (!encodable_order_by.IsNull()) {
    decoded.set_order_by(std::get<EncodableList>(encodable_order_by));
  }
  auto& encodable_limit = list[2];
  if (!encodable_limit.IsNull()) {
    decoded.set_limit(encodable_limit.LongValue());
  }
  auto& encodable_limit_to_last = list[3];
  if (!encodable_limit_to_last.IsNull()) {
    decoded.set_limit_to_last(encodable_limit_to_last.LongValue());
  }
  auto& encodable_start_at = list[4];
  if (!encodable_start_at.IsNull()) {
    decoded.set_start_at(std::get<EncodableList>(encodable_start_at));
  }
  auto& encodable_start_after = list[5];
  if (!encodable_start_after.IsNull()) {
    decoded.set_start_after(std::get<EncodableList>(encodable_start_after));
  }
  auto& encodable_end_at = list[6];
  if (!encodable_end_at.IsNull()) {
    decoded.set_end_at(std::get<EncodableList>(encodable_end_at));
  }
  auto& encodable_end_before = list[7];
  if (!encodable_end_before.IsNull()) {
    decoded.set_end_before(std::get<EncodableList>(encodable_end_before));
  }
  return decoded;
}

// PigeonQueryFilter

PigeonQueryFilter::PigeonQueryFilter(
  const std::string& field,
  const std::string& op)
 : field_(field),
    op_(op) {}

PigeonQueryFilter::PigeonQueryFilter(
  const std::string& field,
  const std::string& op,
  const EncodableValue* value)
 : field_(field),
    op_(op),
    value_(value ? std::optional<EncodableValue>(*value) : std::nullopt) {}

const std::string& PigeonQueryFilter::field() const {
  return field_;
}

void PigeonQueryFilter::set_field(std::string_view value_arg) {
  field_ = value_arg;
}


const std::string& PigeonQueryFilter::op() const {
  return op_;
}

void PigeonQueryFilter::set_op(std::string_view value_arg) {
  op_ = value_arg;
}


const EncodableValue* PigeonQueryFilter::value() const {
  return value_ ? &(*value_) : nullptr;
}

void PigeonQueryFilter::set_value(const EncodableValue* value_arg) {
  value_ = value_arg ? std::optional<EncodableValue>(*value_arg) : std::nullopt;
}

void PigeonQueryFilter::set_value(const EncodableValue& value_arg) {
  value_ = value_arg;
}


EncodableList PigeonQueryFilter::ToEncodableList() const {
  EncodableList list;
  list.reserve(3);
  list.push_back(EncodableValue(field_));
  list.push_back(EncodableValue(op_));
  list.push_back(value_ ? *value_ : EncodableValue());
  return list;
}

PigeonQueryFilter PigeonQueryFilter::FromEncodableList(const EncodableList& list) {
  PigeonQueryFilter decoded(
    std::get<std::string>(list[0]),
    std::get<std::string>(list[1]));
  auto& encodable_value = list[2];
  if (!encodable_value.IsNull()) {
    decoded.set_value(encodable_value);
  }
  return decoded;
}

// PigeonQueryOrder

PigeonQueryOrder::PigeonQueryOrder(
  const std::string& field,
  bool descending)
 : field_(field),
    descending_(descending) {}

const std::string& PigeonQueryOrder::field() const {
  return field_;
}

void PigeonQueryOrder::set_field(std::string_view value_arg) {
  field_ = value_arg;
}


bool PigeonQueryOrder::descending() const {
  return descending_;
}

void PigeonQueryOrder::set_descending(bool value_arg) {
  descending_ = value_arg;
}


EncodableList PigeonQueryOrder::ToEncodableList() const {
  EncodableList list;
  list.reserve(2);
  list.push_back(EncodableValue(field_));
  list.push_back(EncodableValue(descending_));
  return list;
}

PigeonQueryOrder PigeonQueryOrder::FromEncodableList(const EncodableList& list) {
  PigeonQueryOrder decoded(
    std::get<std::string>(list[0]),
    std::get<bool>(list[1]));
  return decoded;
}


FirestoreHostApiCodecSerializer::FirestoreHostApiCodecSerializer() {}

EncodableValue FirestoreHostApiCodecSerializer::ReadValueOfType(
  uint8_t type,
  flutter::ByteStreamReader* stream) const {
  switch (type) {
    case 128:
      return CustomEncodableValue(PigeonAggregateQuerySnapshot::FromEncodableList(std::get<EncodableList>(ReadValue(stream))));
    case 129:
      return CustomEncodableValue(PigeonAggregateResult::FromEncodableList(std::get<EncodableList>(ReadValue(stream))));
    case 130:
      return CustomEncodableValue(PigeonDocumentChange::FromEncodableList(std::get<EncodableList>(ReadValue(stream))));
    case 131:
      return CustomEncodableValue(PigeonDocumentSnapshot::FromEncodableList(std::get<EncodableList>(ReadValue(stream))));
    case 132:
      return CustomEncodableValue(PigeonFirestoreSettings::FromEncodableList(std::get<EncodableList>(ReadValue(stream))));
    case 133:
      return CustomEncodableValue(PigeonGetOptions::FromEncodableList(std::get<EncodableList>(ReadValue(stream))));
    case 134:
      return CustomEncodableValue(PigeonQueryFilter::FromEncodableList(std::get<EncodableList>(ReadValue(stream))));
    case 135:
      return CustomEncodableValue(PigeonQueryOrder::FromEncodableList(std::get<EncodableList>(ReadValue(stream))));
    case 136:
      return CustomEncodableValue(PigeonQueryParameters::FromEncodableList(std::get<EncodableList>(ReadValue(stream))));
    case 137:
      return CustomEncodableValue(PigeonQuerySnapshot::FromEncodableList(std::get<EncodableList>(ReadValue(stream))));
    case 138:
      return CustomEncodableValue(PigeonSetOptions::FromEncodableList(std::get<EncodableList>(ReadValue(stream))));
    case 139:
      return CustomEncodableValue(PigeonSnapshotMetadata::FromEncodableList(std::get<EncodableList>(ReadValue(stream))));
    case 140:
      return CustomEncodableValue(PigeonTransactionUpdate::FromEncodableList(std::get<EncodableList>(ReadValue(stream))));
    default:
      return flutter::StandardCodecSerializer::ReadValueOfType(type, stream);
  }
}

void FirestoreHostApiCodecSerializer::WriteValue(
  const EncodableValue& value,
  flutter::ByteStreamWriter* stream) const {
  if (const CustomEncodableValue* custom_value = std::get_if<CustomEncodableValue>(&value)) {
    if (custom_value->type() == typeid(PigeonAggregateQuerySnapshot)) {
      stream->WriteByte(128);
      WriteValue(EncodableValue(std::any_cast<PigeonAggregateQuerySnapshot>(*custom_value).ToEncodableList()), stream);
      return;
    }
    if (custom_value->type() == typeid(PigeonAggregateResult)) {
      stream->WriteByte(129);
      WriteValue(EncodableValue(std::any_cast<PigeonAggregateResult>(*custom_value).ToEncodableList()), stream);
      return;
    }
    if (custom_value->type() == typeid(PigeonDocumentChange)) {
      stream->WriteByte(130);
      WriteValue(EncodableValue(std::any_cast<PigeonDocumentChange>(*custom_value).ToEncodableList()), stream);
      return;
    }
    if (custom_value->type() == typeid(PigeonDocumentSnapshot)) {
      stream->WriteByte(131);
      WriteValue(EncodableValue(std::any_cast<PigeonDocumentSnapshot>(*custom_value).ToEncodableList()), stream);
      return;
    }
    if (custom_value->type() == typeid(PigeonFirestoreSettings)) {
      stream->WriteByte(132);
      WriteValue(EncodableValue(std::any_cast<PigeonFirestoreSettings>(*custom_value).ToEncodableList()), stream);
      return;
    }
    if (custom_value->type() == typeid(PigeonGetOptions)) {
      stream->WriteByte(133);
      WriteValue(EncodableValue(std::any_cast<PigeonGetOptions>(*custom_value).ToEncodableList()), stream);
      return;
    }
    if (custom_value->type() == typeid(PigeonQueryFilter)) {
      stream->WriteByte(134);
      WriteValue(EncodableValue(std::any_cast<PigeonQueryFilter>(*custom_value).ToEncodableList()), stream);
      return;
    }
    if (custom_value->type() == typeid(PigeonQueryOrder)) {
      stream->WriteByte(135);
      WriteValue(EncodableValue(std::any_cast<PigeonQueryOrder>(*custom_value).ToEncodableList()), stream);
      return;
    }
    if (custom_value->type() == typeid(PigeonQueryParameters)) {
      stream->WriteByte(136);
      WriteValue(EncodableValue(std::any_cast<PigeonQueryParameters>(*custom_value).ToEncodableList()), stream);
      return;
    }
    if (custom_value->type() == typeid(PigeonQuerySnapshot)) {
      stream->WriteByte(137);
      WriteValue(EncodableValue(std::any_cast<PigeonQuerySnapshot>(*custom_value).ToEncodableList()), stream);
      return;
    }
    if (custom_value->type() == typeid(PigeonSetOptions)) {
      stream->WriteByte(138);
      WriteValue(EncodableValue(std::any_cast<PigeonSetOptions>(*custom_value).ToEncodableList()), stream);
      return;
    }
    if (custom_value->type() == typeid(PigeonSnapshotMetadata)) {
      stream->WriteByte(139);
      WriteValue(EncodableValue(std::any_cast<PigeonSnapshotMetadata>(*custom_value).ToEncodableList()), stream);
      return;
    }
    if (custom_value->type() == typeid(PigeonTransactionUpdate)) {
      stream->WriteByte(140);
      WriteValue(EncodableValue(std::any_cast<PigeonTransactionUpdate>(*custom_value).ToEncodableList()), stream);
      return;
    }
  }
  flutter::StandardCodecSerializer::WriteValue(value, stream);
}

/// The codec used by FirestoreHostApi.
const flutter::StandardMessageCodec& FirestoreHostApi::GetCodec() {
  return flutter::StandardMessageCodec::GetInstance(&FirestoreHostApiCodecSerializer::GetInstance());
}

// Sets up an instance of `FirestoreHostApi` to handle messages through the `binary_messenger`.
void FirestoreHostApi::SetUp(
  flutter::BinaryMessenger* binary_messenger,
  FirestoreHostApi* api) {
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.firebase_firestore_webos.FirestoreHostApi.initializeFirestore", &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_app_name_arg = args.at(0);
          if (encodable_app_name_arg.IsNull()) {
            reply(WrapError("app_name_arg unexpectedly null."));
            return;
          }
          const auto& app_name_arg = std::get<std::string>(encodable_app_name_arg);
          const auto& encodable_database_id_arg = args.at(1);
          if (encodable_database_id_arg.IsNull()) {
            reply(WrapError("database_id_arg unexpectedly null."));
            return;
          }
          const auto& database_id_arg = std::get<std::string>(encodable_database_id_arg);
          api->InitializeFirestore(app_name_arg, database_id_arg, [reply](std::optional<FlutterError>&& output) {
            if (output.has_value()) {
              reply(WrapError(output.value()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(EncodableValue());
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.firebase_firestore_webos.FirestoreHostApi.setSettings", &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_app_name_arg = args.at(0);
          if (encodable_app_name_arg.IsNull()) {
            reply(WrapError("app_name_arg unexpectedly null."));
            return;
          }
          const auto& app_name_arg = std::get<std::string>(encodable_app_name_arg);
          const auto& encodable_database_id_arg = args.at(1);
          if (encodable_database_id_arg.IsNull()) {
            reply(WrapError("database_id_arg unexpectedly null."));
            return;
          }
          const auto& database_id_arg = std::get<std::string>(encodable_database_id_arg);
          const auto& encodable_settings_arg = args.at(2);
          if (encodable_settings_arg.IsNull()) {
            reply(WrapError("settings_arg unexpectedly null."));
            return;
          }
          const auto& settings_arg = std::any_cast<const PigeonFirestoreSettings&>(std::get<CustomEncodableValue>(encodable_settings_arg));
          api->SetSettings(app_name_arg, database_id_arg, settings_arg, [reply](std::optional<FlutterError>&& output) {
            if (output.has_value()) {
              reply(WrapError(output.value()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(EncodableValue());
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.firebase_firestore_webos.FirestoreHostApi.enableNetwork", &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_app_name_arg = args.at(0);
          if (encodable_app_name_arg.IsNull()) {
            reply(WrapError("app_name_arg unexpectedly null."));
            return;
          }
          const auto& app_name_arg = std::get<std::string>(encodable_app_name_arg);
          const auto& encodable_database_id_arg = args.at(1);
          if (encodable_database_id_arg.IsNull()) {
            reply(WrapError("database_id_arg unexpectedly null."));
            return;
          }
          const auto& database_id_arg = std::get<std::string>(encodable_database_id_arg);
          api->EnableNetwork(app_name_arg, database_id_arg, [reply](std::optional<FlutterError>&& output) {
            if (output.has_value()) {
              reply(WrapError(output.value()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(EncodableValue());
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.firebase_firestore_webos.FirestoreHostApi.disableNetwork", &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_app_name_arg = args.at(0);
          if (encodable_app_name_arg.IsNull()) {
            reply(WrapError("app_name_arg unexpectedly null."));
            return;
          }
          const auto& app_name_arg = std::get<std::string>(encodable_app_name_arg);
          const auto& encodable_database_id_arg = args.at(1);
          if (encodable_database_id_arg.IsNull()) {
            reply(WrapError("database_id_arg unexpectedly null."));
            return;
          }
          const auto& database_id_arg = std::get<std::string>(encodable_database_id_arg);
          api->DisableNetwork(app_name_arg, database_id_arg, [reply](std::optional<FlutterError>&& output) {
            if (output.has_value()) {
              reply(WrapError(output.value()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(EncodableValue());
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.firebase_firestore_webos.FirestoreHostApi.clearPersistence", &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_app_name_arg = args.at(0);
          if (encodable_app_name_arg.IsNull()) {
            reply(WrapError("app_name_arg unexpectedly null."));
            return;
          }
          const auto& app_name_arg = std::get<std::string>(encodable_app_name_arg);
          const auto& encodable_database_id_arg = args.at(1);
          if (encodable_database_id_arg.IsNull()) {
            reply(WrapError("database_id_arg unexpectedly null."));
            return;
          }
          const auto& database_id_arg = std::get<std::string>(encodable_database_id_arg);
          api->ClearPersistence(app_name_arg, database_id_arg, [reply](std::optional<FlutterError>&& output) {
            if (output.has_value()) {
              reply(WrapError(output.value()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(EncodableValue());
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.firebase_firestore_webos.FirestoreHostApi.terminate", &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_app_name_arg = args.at(0);
          if (encodable_app_name_arg.IsNull()) {
            reply(WrapError("app_name_arg unexpectedly null."));
            return;
          }
          const auto& app_name_arg = std::get<std::string>(encodable_app_name_arg);
          const auto& encodable_database_id_arg = args.at(1);
          if (encodable_database_id_arg.IsNull()) {
            reply(WrapError("database_id_arg unexpectedly null."));
            return;
          }
          const auto& database_id_arg = std::get<std::string>(encodable_database_id_arg);
          api->Terminate(app_name_arg, database_id_arg, [reply](std::optional<FlutterError>&& output) {
            if (output.has_value()) {
              reply(WrapError(output.value()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(EncodableValue());
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.firebase_firestore_webos.FirestoreHostApi.waitForPendingWrites", &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_app_name_arg = args.at(0);
          if (encodable_app_name_arg.IsNull()) {
            reply(WrapError("app_name_arg unexpectedly null."));
            return;
          }
          const auto& app_name_arg = std::get<std::string>(encodable_app_name_arg);
          const auto& encodable_database_id_arg = args.at(1);
          if (encodable_database_id_arg.IsNull()) {
            reply(WrapError("database_id_arg unexpectedly null."));
            return;
          }
          const auto& database_id_arg = std::get<std::string>(encodable_database_id_arg);
          api->WaitForPendingWrites(app_name_arg, database_id_arg, [reply](std::optional<FlutterError>&& output) {
            if (output.has_value()) {
              reply(WrapError(output.value()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(EncodableValue());
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.firebase_firestore_webos.FirestoreHostApi.documentGet", &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_app_name_arg = args.at(0);
          if (encodable_app_name_arg.IsNull()) {
            reply(WrapError("app_name_arg unexpectedly null."));
            return;
          }
          const auto& app_name_arg = std::get<std::string>(encodable_app_name_arg);
          const auto& encodable_database_id_arg = args.at(1);
          if (encodable_database_id_arg.IsNull()) {
            reply(WrapError("database_id_arg unexpectedly null."));
            return;
          }
          const auto& database_id_arg = std::get<std::string>(encodable_database_id_arg);
          const auto& encodable_path_arg = args.at(2);
          if (encodable_path_arg.IsNull()) {
            reply(WrapError("path_arg unexpectedly null."));
            return;
          }
          const auto& path_arg = std::get<std::string>(encodable_path_arg);
          const auto& encodable_options_arg = args.at(3);
          if (encodable_options_arg.IsNull()) {
            reply(WrapError("options_arg unexpectedly null."));
            return;
          }
          const auto& options_arg = std::any_cast<const PigeonGetOptions&>(std::get<CustomEncodableValue>(encodable_options_arg));
          api->DocumentGet(app_name_arg, database_id_arg, path_arg, options_arg, [reply](ErrorOr<PigeonDocumentSnapshot>&& output) {
            if (output.has_error()) {
              reply(WrapError(output.error()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(CustomEncodableValue(std::move(output).TakeValue()));
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.firebase_firestore_webos.FirestoreHostApi.documentSet", &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_app_name_arg = args.at(0);
          if (encodable_app_name_arg.IsNull()) {
            reply(WrapError("app_name_arg unexpectedly null."));
            return;
          }
          const auto& app_name_arg = std::get<std::string>(encodable_app_name_arg);
          const auto& encodable_database_id_arg = args.at(1);
          if (encodable_database_id_arg.IsNull()) {
            reply(WrapError("database_id_arg unexpectedly null."));
            return;
          }
          const auto& database_id_arg = std::get<std::string>(encodable_database_id_arg);
          const auto& encodable_path_arg = args.at(2);
          if (encodable_path_arg.IsNull()) {
            reply(WrapError("path_arg unexpectedly null."));
            return;
          }
          const auto& path_arg = std::get<std::string>(encodable_path_arg);
          const auto& encodable_data_arg = args.at(3);
          if (encodable_data_arg.IsNull()) {
            reply(WrapError("data_arg unexpectedly null."));
            return;
          }
          const auto& data_arg = std::get<EncodableMap>(encodable_data_arg);
          const auto& encodable_options_arg = args.at(4);
          if (encodable_options_arg.IsNull()) {
            reply(WrapError("options_arg unexpectedly null."));
            return;
          }
          const auto& options_arg = std::any_cast<const PigeonSetOptions&>(std::get<CustomEncodableValue>(encodable_options_arg));
          api->DocumentSet(app_name_arg, database_id_arg, path_arg, data_arg, options_arg, [reply](std::optional<FlutterError>&& output) {
            if (output.has_value()) {
              reply(WrapError(output.value()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(EncodableValue());
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.firebase_firestore_webos.FirestoreHostApi.documentUpdate", &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_app_name_arg = args.at(0);
          if (encodable_app_name_arg.IsNull()) {
            reply(WrapError("app_name_arg unexpectedly null."));
            return;
          }
          const auto& app_name_arg = std::get<std::string>(encodable_app_name_arg);
          const auto& encodable_database_id_arg = args.at(1);
          if (encodable_database_id_arg.IsNull()) {
            reply(WrapError("database_id_arg unexpectedly null."));
            return;
          }
          const auto& database_id_arg = std::get<std::string>(encodable_database_id_arg);
          const auto& encodable_path_arg = args.at(2);
          if (encodable_path_arg.IsNull()) {
            reply(WrapError("path_arg unexpectedly null."));
            return;
          }
          const auto& path_arg = std::get<std::string>(encodable_path_arg);
          const auto& encodable_data_arg = args.at(3);
          if (encodable_data_arg.IsNull()) {
            reply(WrapError("data_arg unexpectedly null."));
            return;
          }
          const auto& data_arg = std::get<EncodableMap>(encodable_data_arg);
          api->DocumentUpdate(app_name_arg, database_id_arg, path_arg, data_arg, [reply](std::optional<FlutterError>&& output) {
            if (output.has_value()) {
              reply(WrapError(output.value()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(EncodableValue());
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.firebase_firestore_webos.FirestoreHostApi.documentDelete", &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_app_name_arg = args.at(0);
          if (encodable_app_name_arg.IsNull()) {
            reply(WrapError("app_name_arg unexpectedly null."));
            return;
          }
          const auto& app_name_arg = std::get<std::string>(encodable_app_name_arg);
          const auto& encodable_database_id_arg = args.at(1);
          if (encodable_database_id_arg.IsNull()) {
            reply(WrapError("database_id_arg unexpectedly null."));
            return;
          }
          const auto& database_id_arg = std::get<std::string>(encodable_database_id_arg);
          const auto& encodable_path_arg = args.at(2);
          if (encodable_path_arg.IsNull()) {
            reply(WrapError("path_arg unexpectedly null."));
            return;
          }
          const auto& path_arg = std::get<std::string>(encodable_path_arg);
          api->DocumentDelete(app_name_arg, database_id_arg, path_arg, [reply](std::optional<FlutterError>&& output) {
            if (output.has_value()) {
              reply(WrapError(output.value()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(EncodableValue());
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.firebase_firestore_webos.FirestoreHostApi.documentAddSnapshotListener", &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_app_name_arg = args.at(0);
          if (encodable_app_name_arg.IsNull()) {
            reply(WrapError("app_name_arg unexpectedly null."));
            return;
          }
          const auto& app_name_arg = std::get<std::string>(encodable_app_name_arg);
          const auto& encodable_database_id_arg = args.at(1);
          if (encodable_database_id_arg.IsNull()) {
            reply(WrapError("database_id_arg unexpectedly null."));
            return;
          }
          const auto& database_id_arg = std::get<std::string>(encodable_database_id_arg);
          const auto& encodable_path_arg = args.at(2);
          if (encodable_path_arg.IsNull()) {
            reply(WrapError("path_arg unexpectedly null."));
            return;
          }
          const auto& path_arg = std::get<std::string>(encodable_path_arg);
          const auto& encodable_include_metadata_changes_arg = args.at(3);
          if (encodable_include_metadata_changes_arg.IsNull()) {
            reply(WrapError("include_metadata_changes_arg unexpectedly null."));
            return;
          }
          const auto& include_metadata_changes_arg = std::get<bool>(encodable_include_metadata_changes_arg);
          api->DocumentAddSnapshotListener(app_name_arg, database_id_arg, path_arg, include_metadata_changes_arg, [reply](ErrorOr<int64_t>&& output) {
            if (output.has_error()) {
              reply(WrapError(output.error()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(EncodableValue(std::move(output).TakeValue()));
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.firebase_firestore_webos.FirestoreHostApi.queryGet", &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_app_name_arg = args.at(0);
          if (encodable_app_name_arg.IsNull()) {
            reply(WrapError("app_name_arg unexpectedly null."));
            return;
          }
          const auto& app_name_arg = std::get<std::string>(encodable_app_name_arg);
          const auto& encodable_database_id_arg = args.at(1);
          if (encodable_database_id_arg.IsNull()) {
            reply(WrapError("database_id_arg unexpectedly null."));
            return;
          }
          const auto& database_id_arg = std::get<std::string>(encodable_database_id_arg);
          const auto& encodable_path_arg = args.at(2);
          if (encodable_path_arg.IsNull()) {
            reply(WrapError("path_arg unexpectedly null."));
            return;
          }
          const auto& path_arg = std::get<std::string>(encodable_path_arg);
          const auto& encodable_is_collection_group_arg = args.at(3);
          if (encodable_is_collection_group_arg.IsNull()) {
            reply(WrapError("is_collection_group_arg unexpectedly null."));
            return;
          }
          const auto& is_collection_group_arg = std::get<bool>(encodable_is_collection_group_arg);
          const auto& encodable_parameters_arg = args.at(4);
          if (encodable_parameters_arg.IsNull()) {
            reply(WrapError("parameters_arg unexpectedly null."));
            return;
          }
          const auto& parameters_arg = std::any_cast<const PigeonQueryParameters&>(std::get<CustomEncodableValue>(encodable_parameters_arg));
          const auto& encodable_options_arg = args.at(5);
          if (encodable_options_arg.IsNull()) {
            reply(WrapError("options_arg unexpectedly null."));
            return;
          }
          const auto& options_arg = std::any_cast<const PigeonGetOptions&>(std::get<CustomEncodableValue>(encodable_options_arg));
          api->QueryGet(app_name_arg, database_id_arg, path_arg, is_collection_group_arg, parameters_arg, options_arg, [reply](ErrorOr<PigeonQuerySnapshot>&& output) {
            if (output.has_error()) {
              reply(WrapError(output.error()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(CustomEncodableValue(std::move(output).TakeValue()));
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.firebase_firestore_webos.FirestoreHostApi.queryAddSnapshotListener", &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_app_name_arg = args.at(0);
          if (encodable_app_name_arg.IsNull()) {
            reply(WrapError("app_name_arg unexpectedly null."));
            return;
          }
          const auto& app_name_arg = std::get<std::string>(encodable_app_name_arg);
          const auto& encodable_database_id_arg = args.at(1);
          if (encodable_database_id_arg.IsNull()) {
            reply(WrapError("database_id_arg unexpectedly null."));
            return;
          }
          const auto& database_id_arg = std::get<std::string>(encodable_database_id_arg);
          const auto& encodable_path_arg = args.at(2);
          if (encodable_path_arg.IsNull()) {
            reply(WrapError("path_arg unexpectedly null."));
            return;
          }
          const auto& path_arg = std::get<std::string>(encodable_path_arg);
          const auto& encodable_is_collection_group_arg = args.at(3);
          if (encodable_is_collection_group_arg.IsNull()) {
            reply(WrapError("is_collection_group_arg unexpectedly null."));
            return;
          }
          const auto& is_collection_group_arg = std::get<bool>(encodable_is_collection_group_arg);
          const auto& encodable_parameters_arg = args.at(4);
          if (encodable_parameters_arg.IsNull()) {
            reply(WrapError("parameters_arg unexpectedly null."));
            return;
          }
          const auto& parameters_arg = std::any_cast<const PigeonQueryParameters&>(std::get<CustomEncodableValue>(encodable_parameters_arg));
          const auto& encodable_include_metadata_changes_arg = args.at(5);
          if (encodable_include_metadata_changes_arg.IsNull()) {
            reply(WrapError("include_metadata_changes_arg unexpectedly null."));
            return;
          }
          const auto& include_metadata_changes_arg = std::get<bool>(encodable_include_metadata_changes_arg);
          api->QueryAddSnapshotListener(app_name_arg, database_id_arg, path_arg, is_collection_group_arg, parameters_arg, include_metadata_changes_arg, [reply](ErrorOr<int64_t>&& output) {
            if (output.has_error()) {
              reply(WrapError(output.error()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(EncodableValue(std::move(output).TakeValue()));
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.firebase_firestore_webos.FirestoreHostApi.queryCount", &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_app_name_arg = args.at(0);
          if (encodable_app_name_arg.IsNull()) {
            reply(WrapError("app_name_arg unexpectedly null."));
            return;
          }
          const auto& app_name_arg = std::get<std::string>(encodable_app_name_arg);
          const auto& encodable_database_id_arg = args.at(1);
          if (encodable_database_id_arg.IsNull()) {
            reply(WrapError("database_id_arg unexpectedly null."));
            return;
          }
          const auto& database_id_arg = std::get<std::string>(encodable_database_id_arg);
          const auto& encodable_path_arg = args.at(2);
          if (encodable_path_arg.IsNull()) {
            reply(WrapError("path_arg unexpectedly null."));
            return;
          }
          const auto& path_arg = std::get<std::string>(encodable_path_arg);
          const auto& encodable_is_collection_group_arg = args.at(3);
          if (encodable_is_collection_group_arg.IsNull()) {
            reply(WrapError("is_collection_group_arg unexpectedly null."));
            return;
          }
          const auto& is_collection_group_arg = std::get<bool>(encodable_is_collection_group_arg);
          const auto& encodable_parameters_arg = args.at(4);
          if (encodable_parameters_arg.IsNull()) {
            reply(WrapError("parameters_arg unexpectedly null."));
            return;
          }
          const auto& parameters_arg = std::any_cast<const PigeonQueryParameters&>(std::get<CustomEncodableValue>(encodable_parameters_arg));
          api->QueryCount(app_name_arg, database_id_arg, path_arg, is_collection_group_arg, parameters_arg, [reply](ErrorOr<PigeonAggregateQuerySnapshot>&& output) {
            if (output.has_error()) {
              reply(WrapError(output.error()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(CustomEncodableValue(std::move(output).TakeValue()));
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.firebase_firestore_webos.FirestoreHostApi.queryAggregate", &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_app_name_arg = args.at(0);
          if (encodable_app_name_arg.IsNull()) {
            reply(WrapError("app_name_arg unexpectedly null."));
            return;
          }
          const auto& app_name_arg = std::get<std::string>(encodable_app_name_arg);
          const auto& encodable_database_id_arg = args.at(1);
          if (encodable_database_id_arg.IsNull()) {
            reply(WrapError("database_id_arg unexpectedly null."));
            return;
          }
          const auto& database_id_arg = std::get<std::string>(encodable_database_id_arg);
          const auto& encodable_path_arg = args.at(2);
          if (encodable_path_arg.IsNull()) {
            reply(WrapError("path_arg unexpectedly null."));
            return;
          }
          const auto& path_arg = std::get<std::string>(encodable_path_arg);
          const auto& encodable_is_collection_group_arg = args.at(3);
          if (encodable_is_collection_group_arg.IsNull()) {
            reply(WrapError("is_collection_group_arg unexpectedly null."));
            return;
          }
          const auto& is_collection_group_arg = std::get<bool>(encodable_is_collection_group_arg);
          const auto& encodable_parameters_arg = args.at(4);
          if (encodable_parameters_arg.IsNull()) {
            reply(WrapError("parameters_arg unexpectedly null."));
            return;
          }
          const auto& parameters_arg = std::any_cast<const PigeonQueryParameters&>(std::get<CustomEncodableValue>(encodable_parameters_arg));
          const auto& encodable_aggregate_types_arg = args.at(5);
          if (encodable_aggregate_types_arg.IsNull()) {
            reply(WrapError("aggregate_types_arg unexpectedly null."));
            return;
          }
          const auto& aggregate_types_arg = std::get<EncodableList>(encodable_aggregate_types_arg);
          api->QueryAggregate(app_name_arg, database_id_arg, path_arg, is_collection_group_arg, parameters_arg, aggregate_types_arg, [reply](ErrorOr<PigeonAggregateQuerySnapshot>&& output) {
            if (output.has_error()) {
              reply(WrapError(output.error()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(CustomEncodableValue(std::move(output).TakeValue()));
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.firebase_firestore_webos.FirestoreHostApi.removeSnapshotListener", &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_app_name_arg = args.at(0);
          if (encodable_app_name_arg.IsNull()) {
            reply(WrapError("app_name_arg unexpectedly null."));
            return;
          }
          const auto& app_name_arg = std::get<std::string>(encodable_app_name_arg);
          const auto& encodable_database_id_arg = args.at(1);
          if (encodable_database_id_arg.IsNull()) {
            reply(WrapError("database_id_arg unexpectedly null."));
            return;
          }
          const auto& database_id_arg = std::get<std::string>(encodable_database_id_arg);
          const auto& encodable_listener_id_arg = args.at(2);
          if (encodable_listener_id_arg.IsNull()) {
            reply(WrapError("listener_id_arg unexpectedly null."));
            return;
          }
          const int64_t listener_id_arg = encodable_listener_id_arg.LongValue();
          api->RemoveSnapshotListener(app_name_arg, database_id_arg, listener_id_arg, [reply](std::optional<FlutterError>&& output) {
            if (output.has_value()) {
              reply(WrapError(output.value()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(EncodableValue());
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.firebase_firestore_webos.FirestoreHostApi.useEmulator", &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_app_name_arg = args.at(0);
          if (encodable_app_name_arg.IsNull()) {
            reply(WrapError("app_name_arg unexpectedly null."));
            return;
          }
          const auto& app_name_arg = std::get<std::string>(encodable_app_name_arg);
          const auto& encodable_database_id_arg = args.at(1);
          if (encodable_database_id_arg.IsNull()) {
            reply(WrapError("database_id_arg unexpectedly null."));
            return;
          }
          const auto& database_id_arg = std::get<std::string>(encodable_database_id_arg);
          const auto& encodable_host_arg = args.at(2);
          if (encodable_host_arg.IsNull()) {
            reply(WrapError("host_arg unexpectedly null."));
            return;
          }
          const auto& host_arg = std::get<std::string>(encodable_host_arg);
          const auto& encodable_port_arg = args.at(3);
          if (encodable_port_arg.IsNull()) {
            reply(WrapError("port_arg unexpectedly null."));
            return;
          }
          const int64_t port_arg = encodable_port_arg.LongValue();
          api->UseEmulator(app_name_arg, database_id_arg, host_arg, port_arg, [reply](std::optional<FlutterError>&& output) {
            if (output.has_value()) {
              reply(WrapError(output.value()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(EncodableValue());
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.firebase_firestore_webos.FirestoreHostApi.setLoggingEnabled", &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_app_name_arg = args.at(0);
          if (encodable_app_name_arg.IsNull()) {
            reply(WrapError("app_name_arg unexpectedly null."));
            return;
          }
          const auto& app_name_arg = std::get<std::string>(encodable_app_name_arg);
          const auto& encodable_database_id_arg = args.at(1);
          if (encodable_database_id_arg.IsNull()) {
            reply(WrapError("database_id_arg unexpectedly null."));
            return;
          }
          const auto& database_id_arg = std::get<std::string>(encodable_database_id_arg);
          const auto& encodable_enabled_arg = args.at(2);
          if (encodable_enabled_arg.IsNull()) {
            reply(WrapError("enabled_arg unexpectedly null."));
            return;
          }
          const auto& enabled_arg = std::get<bool>(encodable_enabled_arg);
          api->SetLoggingEnabled(app_name_arg, database_id_arg, enabled_arg, [reply](std::optional<FlutterError>&& output) {
            if (output.has_value()) {
              reply(WrapError(output.value()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(EncodableValue());
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.firebase_firestore_webos.FirestoreHostApi.batchCommit", &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_app_name_arg = args.at(0);
          if (encodable_app_name_arg.IsNull()) {
            reply(WrapError("app_name_arg unexpectedly null."));
            return;
          }
          const auto& app_name_arg = std::get<std::string>(encodable_app_name_arg);
          const auto& encodable_database_id_arg = args.at(1);
          if (encodable_database_id_arg.IsNull()) {
            reply(WrapError("database_id_arg unexpectedly null."));
            return;
          }
          const auto& database_id_arg = std::get<std::string>(encodable_database_id_arg);
          const auto& encodable_writes_arg = args.at(2);
          if (encodable_writes_arg.IsNull()) {
            reply(WrapError("writes_arg unexpectedly null."));
            return;
          }
          const auto& writes_arg = std::get<EncodableList>(encodable_writes_arg);
          api->BatchCommit(app_name_arg, database_id_arg, writes_arg, [reply](std::optional<FlutterError>&& output) {
            if (output.has_value()) {
              reply(WrapError(output.value()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(EncodableValue());
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.firebase_firestore_webos.FirestoreHostApi.runTransaction", &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_app_name_arg = args.at(0);
          if (encodable_app_name_arg.IsNull()) {
            reply(WrapError("app_name_arg unexpectedly null."));
            return;
          }
          const auto& app_name_arg = std::get<std::string>(encodable_app_name_arg);
          const auto& encodable_database_id_arg = args.at(1);
          if (encodable_database_id_arg.IsNull()) {
            reply(WrapError("database_id_arg unexpectedly null."));
            return;
          }
          const auto& database_id_arg = std::get<std::string>(encodable_database_id_arg);
          const auto& encodable_transaction_id_arg = args.at(2);
          if (encodable_transaction_id_arg.IsNull()) {
            reply(WrapError("transaction_id_arg unexpectedly null."));
            return;
          }
          const int64_t transaction_id_arg = encodable_transaction_id_arg.LongValue();
          const auto& encodable_max_attempts_arg = args.at(3);
          if (encodable_max_attempts_arg.IsNull()) {
            reply(WrapError("max_attempts_arg unexpectedly null."));
            return;
          }
          const int64_t max_attempts_arg = encodable_max_attempts_arg.LongValue();
          api->RunTransaction(app_name_arg, database_id_arg, transaction_id_arg, max_attempts_arg, [reply](std::optional<FlutterError>&& output) {
            if (output.has_value()) {
              reply(WrapError(output.value()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(EncodableValue());
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.firebase_firestore_webos.FirestoreHostApi.transactionGet", &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_app_name_arg = args.at(0);
          if (encodable_app_name_arg.IsNull()) {
            reply(WrapError("app_name_arg unexpectedly null."));
            return;
          }
          const auto& app_name_arg = std::get<std::string>(encodable_app_name_arg);
          const auto& encodable_database_id_arg = args.at(1);
          if (encodable_database_id_arg.IsNull()) {
            reply(WrapError("database_id_arg unexpectedly null."));
            return;
          }
          const auto& database_id_arg = std::get<std::string>(encodable_database_id_arg);
          const auto& encodable_transaction_id_arg = args.at(2);
          if (encodable_transaction_id_arg.IsNull()) {
            reply(WrapError("transaction_id_arg unexpectedly null."));
            return;
          }
          const int64_t transaction_id_arg = encodable_transaction_id_arg.LongValue();
          const auto& encodable_path_arg = args.at(3);
          if (encodable_path_arg.IsNull()) {
            reply(WrapError("path_arg unexpectedly null."));
            return;
          }
          const auto& path_arg = std::get<std::string>(encodable_path_arg);
          api->TransactionGet(app_name_arg, database_id_arg, transaction_id_arg, path_arg, [reply](ErrorOr<PigeonDocumentSnapshot>&& output) {
            if (output.has_error()) {
              reply(WrapError(output.error()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(CustomEncodableValue(std::move(output).TakeValue()));
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.firebase_firestore_webos.FirestoreHostApi.transactionComplete", &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_app_name_arg = args.at(0);
          if (encodable_app_name_arg.IsNull()) {
            reply(WrapError("app_name_arg unexpectedly null."));
            return;
          }
          const auto& app_name_arg = std::get<std::string>(encodable_app_name_arg);
          const auto& encodable_database_id_arg = args.at(1);
          if (encodable_database_id_arg.IsNull()) {
            reply(WrapError("database_id_arg unexpectedly null."));
            return;
          }
          const auto& database_id_arg = std::get<std::string>(encodable_database_id_arg);
          const auto& encodable_transaction_id_arg = args.at(2);
          if (encodable_transaction_id_arg.IsNull()) {
            reply(WrapError("transaction_id_arg unexpectedly null."));
            return;
          }
          const int64_t transaction_id_arg = encodable_transaction_id_arg.LongValue();
          const auto& encodable_result_type_arg = args.at(3);
          if (encodable_result_type_arg.IsNull()) {
            reply(WrapError("result_type_arg unexpectedly null."));
            return;
          }
          const PigeonTransactionResult& result_type_arg = (PigeonTransactionResult)encodable_result_type_arg.LongValue();
          const auto& encodable_updates_arg = args.at(4);
          const auto* updates_arg = std::get_if<EncodableList>(&encodable_updates_arg);
          api->TransactionComplete(app_name_arg, database_id_arg, transaction_id_arg, result_type_arg, updates_arg, [reply](std::optional<FlutterError>&& output) {
            if (output.has_value()) {
              reply(WrapError(output.value()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(EncodableValue());
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
}

EncodableValue FirestoreHostApi::WrapError(std::string_view error_message) {
  return EncodableValue(EncodableList{
    EncodableValue(std::string(error_message)),
    EncodableValue("Error"),
    EncodableValue()
  });
}

EncodableValue FirestoreHostApi::WrapError(const FlutterError& error) {
  return EncodableValue(EncodableList{
    EncodableValue(error.code()),
    EncodableValue(error.message()),
    error.details()
  });
}

// Generated class from Pigeon that represents Flutter messages that can be called from C++.
FirestoreFlutterApi::FirestoreFlutterApi(flutter::BinaryMessenger* binary_messenger)
 : binary_messenger_(binary_messenger) {}

const flutter::StandardMessageCodec& FirestoreFlutterApi::GetCodec() {
  return flutter::StandardMessageCodec::GetInstance(&flutter::StandardCodecSerializer::GetInstance());
}

void FirestoreFlutterApi::OnTransactionCallback(
  const std::string& app_name_arg,
  const std::string& database_id_arg,
  int64_t transaction_id_arg,
  std::function<void(void)>&& on_success,
  std::function<void(const FlutterError&)>&& on_error) {
  const std::string channel_name = "dev.flutter.pigeon.firebase_firestore_webos.FirestoreFlutterApi.onTransactionCallback";
  BasicMessageChannel<> channel(binary_messenger_, channel_name, &GetCodec());
  EncodableValue encoded_api_arguments = EncodableValue(EncodableList{
    EncodableValue(app_name_arg),
    EncodableValue(database_id_arg),
    EncodableValue(transaction_id_arg),
  });
  channel.Send(encoded_api_arguments, [channel_name, on_success = std::move(on_success), on_error = std::move(on_error)](const uint8_t* reply, size_t reply_size) {
    std::unique_ptr<EncodableValue> response = GetCodec().DecodeMessage(reply, reply_size);
    const auto& encodable_return_value = *response;
    const auto* list_return_value = std::get_if<EncodableList>(&encodable_return_value);
    if (list_return_value) {
      if (list_return_value->size() > 1) {
        on_error(FlutterError(std::get<std::string>(list_return_value->at(0)), std::get<std::string>(list_return_value->at(1)), list_return_value->at(2)));
      } else {
        on_success();
      }
    } else {
      on_error(CreateConnectionError(channel_name));
    } 
  });
}

}  // namespace firebase_firestore_webos
