// Autogenerated from Pigeon (v17.3.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import, no_leading_underscores_for_local_identifiers

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

PlatformException _createConnectionError(String channelName) {
  return PlatformException(
    code: 'channel-error',
    message: 'Unable to establish connection on channel: "$channelName".',
  );
}

/// All configurable options for a Firebase App.
class FirebaseOptionsPigeon {
  FirebaseOptionsPigeon({
    required this.apiKey,
    required this.appId,
    required this.projectId,
    this.messagingSenderId,
    this.databaseUrl,
    this.storageBucket,
    this.authDomain,
  });

  String apiKey;

  String appId;

  String projectId;

  String? messagingSenderId;

  String? databaseUrl;

  String? storageBucket;

  String? authDomain;

  Object encode() {
    return <Object?>[
      apiKey,
      appId,
      projectId,
      messagingSenderId,
      databaseUrl,
      storageBucket,
      authDomain,
    ];
  }

  static FirebaseOptionsPigeon decode(Object result) {
    result as List<Object?>;
    return FirebaseOptionsPigeon(
      apiKey: result[0]! as String,
      appId: result[1]! as String,
      projectId: result[2]! as String,
      messagingSenderId: result[3] as String?,
      databaseUrl: result[4] as String?,
      storageBucket: result[5] as String?,
      authDomain: result[6] as String?,
    );
  }
}

/// Represents an initialized Firebase App returned to Dart.
class FirebaseAppPigeon {
  FirebaseAppPigeon({
    required this.name,
    required this.options,
  });

  /// App name – "[DEFAULT]" for the default app.
  String name;

  /// The options that were used to initialize this app.
  FirebaseOptionsPigeon options;

  Object encode() {
    return <Object?>[
      name,
      options.encode(),
    ];
  }

  static FirebaseAppPigeon decode(Object result) {
    result as List<Object?>;
    return FirebaseAppPigeon(
      name: result[0]! as String,
      options: FirebaseOptionsPigeon.decode(result[1]! as List<Object?>),
    );
  }
}

class _FirebaseCoreHostApiCodec extends StandardMessageCodec {
  const _FirebaseCoreHostApiCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is FirebaseAppPigeon) {
      buffer.putUint8(128);
      writeValue(buffer, value.encode());
    } else if (value is FirebaseOptionsPigeon) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 128: 
        return FirebaseAppPigeon.decode(readValue(buffer)!);
      case 129: 
        return FirebaseOptionsPigeon.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class FirebaseCoreHostApi {
  /// Constructor for [FirebaseCoreHostApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  FirebaseCoreHostApi({BinaryMessenger? binaryMessenger})
      : __pigeon_binaryMessenger = binaryMessenger;
  final BinaryMessenger? __pigeon_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _FirebaseCoreHostApiCodec();

  Future<void> setDataDirectory(String dataDirectory) async {
    const String __pigeon_channelName = 'dev.flutter.pigeon.firebase_core_webos.FirebaseCoreHostApi.setDataDirectory';
    final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(<Object?>[dataDirectory]) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<FirebaseAppPigeon> initializeApp(String appName, FirebaseOptionsPigeon options) async {
    const String __pigeon_channelName = 'dev.flutter.pigeon.firebase_core_webos.FirebaseCoreHostApi.initializeApp';
    final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(<Object?>[appName, options]) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else if (__pigeon_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (__pigeon_replyList[0] as FirebaseAppPigeon?)!;
    }
  }

  Future<FirebaseAppPigeon> getApp(String appName) async {
    const String __pigeon_channelName = 'dev.flutter.pigeon.firebase_core_webos.FirebaseCoreHostApi.getApp';
    final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(<Object?>[appName]) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else if (__pigeon_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (__pigeon_replyList[0] as FirebaseAppPigeon?)!;
    }
  }

  Future<void> deleteApp(String appName) async {
    const String __pigeon_channelName = 'dev.flutter.pigeon.firebase_core_webos.FirebaseCoreHostApi.deleteApp';
    final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(<Object?>[appName]) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else {
      return;
    }
  }
}
