name: firebase_firestore_webos_example
description: Demonstrates how to use the firebase_firestore_webos plugin.
publish_to: 'none'

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  firebase_core: any
  cloud_firestore: any
  firebase_core_webos:
    path: ../../firebase_core/
  
  firebase_firestore_webos:
      path: ../

  cupertino_icons: ^1.0.8

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true